app = 'nova-hg8spq'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[deploy]
  strategy = "immediate"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256