# fly.toml app configuration file generated for nova-hg8spq on 2026-05-13T04:25:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nova-hg8spq'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
