import type { EquipmentSlot, IEquipmentStat } from '@nova/db';
import type { Rarity } from '../utils';

export interface EquipmentData {
  id: string;
  name: string;
  emoji: string;
  type: 'equipment';
  slot: EquipmentSlot;
  rarity: Rarity;
  sellPrice: number;
  description: string;
  stats: IEquipmentStat;
}

export const EQUIPMENTS: Record<string, EquipmentData> = {
  slime_boots: {
    id: 'slime_boots',
    name: 'Slime Boots',
    emoji: '👢🟢',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Common',
    sellPrice: 60,
    description: 'Sepatu dari lendir. Licin tapi nambah HP.',
    stats: { hp: 10 },
  },
  boar_tusk_helm: {
    id: 'boar_tusk_helm',
    name: 'Helm Taring Babi',
    emoji: '🐗⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Uncommon',
    sellPrice: 80,
    description: 'Helm dari taring babi. +HP',
    stats: { hp: 15, def: 1 },
  },
  goblin_dagger: {
    id: 'goblin_dagger',
    name: 'Belati Karat',
    emoji: '🗡️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 40,
    description: 'Belati curian, masih bisa dipakai',
    stats: { atk: 6, critRate: 0.03, classLock: ['rogue'] },
  },
  hunter_bow: {
    id: 'hunter_bow',
    name: 'Hunter Bow',
    emoji: '🏹',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 70,
    description: 'Busur pemburu. Crit damage tinggi buat rogue.',
    stats: { atk: 15, critDmg: 1.8 },
  },
  ice_club: {
    id: 'ice_club',
    name: 'Gada Es',
    emoji: '🥶',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 95,
    description: 'Membekukan musuh',
    stats: { atk: 18, def: 2, classLock: ['warrior'] },
  },
  iron_gauntlet: {
    id: 'iron_gauntlet',
    name: 'Iron Gauntlet',
    emoji: '🧤⚙️',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Uncommon',
    sellPrice: 120,
    description: 'Sarung tangan besi. +ATK',
    stats: { atk: 5, def: 1, classLock: ['warrior'] },
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    emoji: '⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 45,
    description: 'Pedang besi standar warrior. Balance ATK.',
    stats: { atk: 12 },
  },
  lizard_scale_armor: {
    id: 'lizard_scale_armor',
    name: 'Armor Sisik Kadal',
    emoji: '🦎🛡️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Uncommon',
    sellPrice: 90,
    description: 'Armor ringan dari sisik kadal. +HP +DEF',
    stats: { hp: 12, def: 2 },
  },
  mage_staff: {
    id: 'mage_staff',
    name: 'Mage Staff',
    emoji: '🪄',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 50,
    description: 'Tongkat mage. Naikin ATK + crit dikit buat early.',
    stats: { atk: 10, critRate: 0.05 },
  },
  rusted_sword: {
    id: 'rusted_sword',
    name: 'Pedang Karat',
    emoji: '⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 45,
    description: 'Masih bisa diasah',
    stats: { atk: 8, classLock: ['warrior'] },
  },
  war_axe: {
    id: 'war_axe',
    name: 'Kapak Perang',
    emoji: '🪓',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 70,
    description: 'Berat tapi mematikan',
    stats: { atk: 12, classLock: ['warrior'] },
  },
  bear_paw_gauntlet: {
    id: 'bear_paw_gauntlet',
    name: 'Gauntlet Cakar Beruang',
    emoji: '🐻🧤',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Rare',
    sellPrice: 180,
    description: 'Sarung tangan dari cakar beruang. +ATK +HP',
    stats: { atk: 10, hp: 20, classLock: ['warrior'] },
  },
  bone_helm: {
    id: 'bone_helm',
    name: 'Helm Tengkorak',
    emoji: '💀⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 160,
    description: 'Helm dari tengkorak. +DEF +HP',
    stats: { def: 3, hp: 15 },
  },
  drake_claw_dagger: {
    id: 'drake_claw_dagger',
    name: 'Drake Claw Dagger',
    emoji: '🗡️🐲',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 250,
    description: 'Belati dari cakar drake. +ATK +Crit',
    stats: { atk: 12, critRate: 0.05, critDmg: 0.2, classLock: ['rogue'] },
  },
  harpy_bow: {
    id: 'harpy_bow',
    name: 'Busur Harpy',
    emoji: '🏹🦅',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 220,
    description: 'Busur dari sayap harpy. +ATK +CritRate',
    stats: { atk: 16, critRate: 0.06, classLock: ['rogue'] },
  },
  lava_boots: {
    id: 'lava_boots',
    name: 'Sepatu Lava',
    emoji: '👢🔥',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Rare',
    sellPrice: 200,
    description: 'Sepatu tahan lava. +HP +DEF',
    stats: { hp: 25, def: 3 },
  },
  slime_crown: {
    id: 'slime_crown',
    name: 'Slime Crown',
    emoji: '👑',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 150,
    description: 'Mahkota asli Raja Slime. Lengket tapi bawa hoki + HP.',
    stats: { hp: 20, critRate: 0.05 },
  },
  specter_hood: {
    id: 'specter_hood',
    name: 'Specter Hood',
    emoji: '👻🎩',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 200,
    description: 'Tudung hantu. +Crit Rate',
    stats: { critRate: 0.08, hp: 15, classLock: ['rogue', 'mage'] },
  },
  spider_fang_dagger: {
    id: 'spider_fang_dagger',
    name: 'Belati Taring Laba-laba',
    emoji: '🗡️🕷️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 200,
    description: 'Belati beracun. +ATK +CritDmg',
    stats: { atk: 14, critDmg: 0.3, classLock: ['rogue'] },
  },
  wolf_fang_necklace: {
    id: 'wolf_fang_necklace',
    name: 'Kalung Taring Serigala',
    emoji: '🐺📿',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Rare',
    sellPrice: 150,
    description: 'Kalung dari taring alpha. +ATK +Crit',
    stats: { atk: 8, critRate: 0.05 },
  },
  berserker_armor: {
    id: 'berserker_armor',
    name: 'Armor Berserk',
    emoji: '👹🛡️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 400,
    description: 'Armor orc berserk. +ATK +HP +DEF',
    stats: { atk: 15, hp: 30, def: 4, classLock: ['warrior'] },
  },
  desert_scale_armor: {
    id: 'desert_scale_armor',
    name: 'Armor Sisik Gurun',
    emoji: '🛡️🏜️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 550,
    description: 'Armor sisik gurun',
    stats: { hp: 40, def: 7 },
  },
  frost_cape: {
    id: 'frost_cape',
    name: 'Jubah Beku',
    emoji: '🧥❄️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 480,
    description: 'Jubah troll es. +HP +DEF +CritDmg',
    stats: { hp: 45, def: 6, critDmg: 0.2 },
  },
  obsidian_plate: {
    id: 'obsidian_plate',
    name: 'Obsidian Plate',
    emoji: '⬛',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 280,
    description: 'Pelat obsidian dari Heart of Crystal. DEF + HP tebel.',
    stats: { hp: 50, def: 5 },
  },
  reaper_scythe: {
    id: 'reaper_scythe',
    name: 'Reaper Scythe',
    emoji: '☠️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Epic',
    sellPrice: 450,
    description: 'Sabit Void Reaper. Crit monster. Drop dari Boss Floor 30.',
    stats: { atk: 25, critRate: 0.1, critDmg: 2.0 },
  },
  shadow_cloak: {
    id: 'shadow_cloak',
    name: 'Jubah Bayangan',
    emoji: '🥷🌑',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 450,
    description: 'Jubah panther. +CritRate +ATK',
    stats: { critRate: 0.08, atk: 12, classLock: ['rogue'] },
  },
  star_blade: {
    id: 'star_blade',
    name: 'Star Blade',
    emoji: '⚔️⭐',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Epic',
    sellPrice: 800,
    description: 'Pedang dari bintang. +ATK +CritDmg',
    stats: { atk: 20, critRate: 0.05, critDmg: 0.3, classLock: ['warrior', 'rogue'] },
  },
  warden_cape: {
    id: 'warden_cape',
    name: 'Warden Cape',
    emoji: '🧥❄️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 500,
    description: 'Jubah warden. +HP +DEF',
    stats: { hp: 40, def: 6, classLock: ['warrior', 'mage'] },
  },
  warden_chain: {
    id: 'warden_chain',
    name: 'Warden Chain',
    emoji: '⛓️',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Epic',
    sellPrice: 500,
    description: 'Rantai penjaga yang tak terpatahkan',
    stats: { def: 8, hp: 40 },
  },
  inferno_staff: {
    id: 'inferno_staff',
    name: 'Inferno Staff',
    emoji: '🔥🪄',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Legendary',
    sellPrice: 1000,
    description: 'Tongkat api naga. +ATK +CritDmg',
    stats: { atk: 30, critDmg: 0.4, classLock: ['mage'] },
  },
  orc_warchief_helm: {
    id: 'orc_warchief_helm',
    name: 'Helm Warchief',
    emoji: '⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Legendary',
    sellPrice: 520,
    description: 'Mahkota para orc',
    stats: { hp: 35, def: 5, critRate: 0.05 },
  },
  void_crown: {
    id: 'void_crown',
    name: 'Void Crown',
    emoji: '👑🌫️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Legendary',
    sellPrice: 800,
    description: 'Mahkota kehampaan',
    stats: { atk: 15, critRate: 0.15, hp: 30 },
  },
  nova_blade: {
    id: 'nova_blade',
    name: 'Nova Blade',
    emoji: '🌟⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Mythic',
    sellPrice: 5000,
    description: 'Pedang dari inti nova. +ATK +Crit +HP',
    stats: { atk: 40, critRate: 0.1, critDmg: 0.5, hp: 50 },
  },
};

export function getEquipment(id: string): EquipmentData | null {
  return EQUIPMENTS[id] ?? null;
}

export function getAllEquipments(): EquipmentData[] {
  return Object.values(EQUIPMENTS);
}

export function getEquipmentsBySlot(slot: EquipmentSlot): EquipmentData[] {
  return getAllEquipments().filter((e) => e.slot === slot);
}
