import type { EquipmentSlot, IEquipmentStat } from '@nova/db';
import type { Rarity } from '../utils.ts';

export interface EquipmentData {
  id: string;
  emoji: string;
  type: 'equipment';
  slot: EquipmentSlot;
  rarity: Rarity;
  sellPrice: number;
  stats: IEquipmentStat;
}

export const EQUIPMENTS: Record<string, EquipmentData> = {
  // === COMMON-UNCOMMON ===
  slime_boots: {
    id: 'slime_boots',
    emoji: '👢🟢',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Common',
    sellPrice: 60,
    stats: { hp: 10 },
  },
  boar_tusk_helm: {
    id: 'boar_tusk_helm',
    emoji: '🐗⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Uncommon',
    sellPrice: 80,
    stats: { hp: 15, def: 1 },
  },
  goblin_dagger: {
    id: 'goblin_dagger',
    emoji: '🗡️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 40,
    stats: { atk: 6, critRate: 0.03, classLock: ['rogue'], element: 'physical' },
  },
  hunter_bow: {
    id: 'hunter_bow',
    emoji: '🏹',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 70,
    stats: { atk: 15, critDmg: 1.8, element: 'physical' },
  },
  ice_club: {
    id: 'ice_club',
    emoji: '🥶',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 95,
    stats: { atk: 18, def: 2, classLock: ['warrior'], element: 'ice' },
  },
  iron_gauntlet: {
    id: 'iron_gauntlet',
    emoji: '🧤⚙️',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Uncommon',
    sellPrice: 120,
    stats: { atk: 5, def: 1, classLock: ['warrior'] },
  },
  iron_sword: {
    id: 'iron_sword',
    emoji: '⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 45,
    stats: { atk: 12, element: 'physical' },
  },
  lizard_scale_armor: {
    id: 'lizard_scale_armor',
    emoji: '🦎🛡️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Uncommon',
    sellPrice: 90,
    stats: { hp: 12, def: 2 },
  },
  mage_staff: {
    id: 'mage_staff',
    emoji: '🪄',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 50,
    stats: { atk: 10, critRate: 0.05, element: 'physical' },
  },
  rusted_sword: {
    id: 'rusted_sword',
    emoji: '⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 45,
    stats: { atk: 8, classLock: ['warrior'], element: 'physical' },
  },
  war_axe: {
    id: 'war_axe',
    emoji: '🪓',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Uncommon',
    sellPrice: 70,
    stats: { atk: 12, classLock: ['warrior'], element: 'physical' },
  },

  // === RARE ===
  bear_paw_gauntlet: {
    id: 'bear_paw_gauntlet',
    emoji: '🐻🧤',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Rare',
    sellPrice: 180,
    stats: { atk: 10, hp: 20, classLock: ['warrior'] },
  },
  bone_helm: {
    id: 'bone_helm',
    emoji: '💀⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 160,
    stats: { def: 3, hp: 15 },
  },
  drake_claw_dagger: {
    id: 'drake_claw_dagger',
    emoji: '🗡️🐲',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 250,
    stats: { atk: 12, critRate: 0.05, critDmg: 0.2, classLock: ['rogue'], element: 'water' },
  },
  harpy_bow: {
    id: 'harpy_bow',
    emoji: '🏹🦅',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 220,
    stats: { atk: 16, critRate: 0.06, classLock: ['rogue'], element: 'wind' },
  },
  lava_boots: {
    id: 'lava_boots',
    emoji: '👢🔥',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Rare',
    sellPrice: 200,
    stats: { hp: 25, def: 3, element: 'fire' },
  },
  slime_crown: {
    id: 'slime_crown',
    emoji: '👑',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 150,
    stats: { hp: 20, critRate: 0.05 },
  },
  specter_hood: {
    id: 'specter_hood',
    emoji: '👻🎩',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Rare',
    sellPrice: 200,
    stats: { critRate: 0.08, hp: 15, classLock: ['rogue', 'mage'] },
  },
  spider_fang_dagger: {
    id: 'spider_fang_dagger',
    emoji: '🗡️🕷️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 200,
    stats: { atk: 14, critDmg: 0.3, classLock: ['rogue'], element: 'physical' },
  },
  wolf_fang_necklace: {
    id: 'wolf_fang_necklace',
    emoji: '🐺📿',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Rare',
    sellPrice: 150,
    stats: { atk: 8, critRate: 0.05 },
  },
  cursed_blade: {
    id: 'cursed_blade',
    emoji: '🗡️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Rare',
    sellPrice: 240,
    stats: { atk: 22, critRate: 0.06, classLock: ['warrior'], element: 'dark' },
  },

  // === EPIC ===
  berserker_armor: {
    id: 'berserker_armor',
    emoji: '👹🛡️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 400,
    stats: { atk: 15, hp: 30, def: 4, classLock: ['warrior'] },
  },
  desert_scale_armor: {
    id: 'desert_scale_armor',
    emoji: '🛡️🏜️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 550,
    stats: { hp: 40, def: 7 },
  },
  frost_cape: {
    id: 'frost_cape',
    emoji: '🧥❄️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 480,
    stats: { hp: 45, def: 6, critDmg: 0.2, element: 'ice' },
  },
  obsidian_plate: {
    id: 'obsidian_plate',
    emoji: '⬛',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 280,
    stats: { hp: 50, def: 5 },
  },
  reaper_scythe: {
    id: 'reaper_scythe',
    emoji: '☠️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Epic',
    sellPrice: 450,
    stats: { atk: 25, critRate: 0.1, critDmg: 2.0, element: 'dark' },
  },
  shadow_cloak: {
    id: 'shadow_cloak',
    emoji: '🥷🌑',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 450,
    stats: { critRate: 0.08, atk: 12, classLock: ['rogue'] },
  },
  star_blade: {
    id: 'star_blade',
    emoji: '⚔️⭐',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Epic',
    sellPrice: 800,
    stats: {
      atk: 20,
      critRate: 0.05,
      critDmg: 0.3,
      classLock: ['warrior', 'rogue'],
      element: 'light',
    },
  },
  warden_cape: {
    id: 'warden_cape',
    emoji: '🧥❄️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Epic',
    sellPrice: 500,
    stats: { hp: 40, def: 6, classLock: ['warrior', 'mage'] },
  },
  warden_chain: {
    id: 'warden_chain',
    emoji: '⛓️',
    type: 'equipment',
    slot: 'accessory',
    rarity: 'Epic',
    sellPrice: 500,
    stats: { def: 8, hp: 40 },
  },
  thunder_bow: {
    id: 'thunder_bow',
    emoji: '🏹⚡',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Epic',
    sellPrice: 600,
    stats: { atk: 25, critRate: 0.08, critDmg: 0.3, classLock: ['rogue'], element: 'lightning' },
  },

  // === LEGENDARY ===
  inferno_staff: {
    id: 'inferno_staff',
    emoji: '🔥🪄',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Legendary',
    sellPrice: 1000,
    stats: { atk: 30, critDmg: 0.4, classLock: ['mage'], element: 'fire' },
  },
  orc_warchief_helm: {
    id: 'orc_warchief_helm',
    emoji: '⛑️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Legendary',
    sellPrice: 520,
    stats: { hp: 35, def: 5, critRate: 0.05 },
  },
  void_crown: {
    id: 'void_crown',
    emoji: '👑🌫️',
    type: 'equipment',
    slot: 'helmet',
    rarity: 'Legendary',
    sellPrice: 800,
    stats: { atk: 15, critRate: 0.15, hp: 30 },
  },
  void_armor: {
    id: 'void_armor',
    emoji: '🛡️🕳️',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Legendary',
    sellPrice: 900,
    stats: { def: 10, hp: 50, atk: 15 },
  },
  crystal_staff: {
    id: 'crystal_staff',
    emoji: '🪄💎',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Legendary',
    sellPrice: 1100,
    stats: { atk: 28, critDmg: 0.4, hp: 30, classLock: ['mage'], element: 'light' },
  },
  hydra_venom_dagger: {
    id: 'hydra_venom_dagger',
    emoji: '🗡️🐉',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Legendary',
    sellPrice: 1200,
    stats: { atk: 35, critRate: 0.1, critDmg: 0.4, classLock: ['rogue'], element: 'water' },
  },

  // === MYTHIC ===
  nova_blade: {
    id: 'nova_blade',
    emoji: '🌟⚔️',
    type: 'equipment',
    slot: 'weapon',
    rarity: 'Mythic',
    sellPrice: 5000,
    stats: { atk: 40, critRate: 0.1, critDmg: 0.5, hp: 50, element: 'light' },
  },
  phoenix_wings: {
    id: 'phoenix_wings',
    emoji: '🔥🪽',
    type: 'equipment',
    slot: 'armor',
    rarity: 'Mythic',
    sellPrice: 3000,
    stats: { atk: 40, critDmg: 0.5, hp: 60, element: 'fire' },
  },

  // === TOOLS ===
  wooden_rod: {
    id: 'wooden_rod',
    emoji: '🎣',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Common',
    sellPrice: 50,
    stats: { fishBonus: 0.1 },
  },
  iron_rod: {
    id: 'iron_rod',
    emoji: '🎣',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Uncommon',
    sellPrice: 150,
    stats: { fishBonus: 0.2 },
  },
  mythril_rod: {
    id: 'mythril_rod',
    emoji: '✨🎣',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Rare',
    sellPrice: 400,
    stats: { fishBonus: 0.35 },
  },
  abyssal_rod: {
    id: 'abyssal_rod',
    emoji: '🌊🎣',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Epic',
    sellPrice: 1200,
    stats: { fishBonus: 0.5 },
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    emoji: '⛏️',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Common',
    sellPrice: 40,
    stats: { mineBonus: 0.1 },
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    emoji: '⛏️',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Uncommon',
    sellPrice: 140,
    stats: { mineBonus: 0.2 },
  },
  mythril_pickaxe: {
    id: 'mythril_pickaxe',
    emoji: '✨⛏️',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Rare',
    sellPrice: 380,
    stats: { mineBonus: 0.35 },
  },
  forager_bag: {
    id: 'forager_bag',
    emoji: '🎒',
    type: 'equipment',
    slot: 'tool',
    rarity: 'Uncommon',
    sellPrice: 120,
    stats: { gatherBonus: 0.15 },
  },
};

export const getEquipment = (id: string) => EQUIPMENTS[id] ?? null;
export const getAllEquipments = () => Object.values(EQUIPMENTS);
export const getEquipmentsBySlot = (slot: EquipmentSlot) => getAllEquipments().filter((e) => e.slot === slot);
