import { i18nItem, i18nItemDesc, i18nFish, i18nFishDesc } from '../i18n/display';
import type { TFunction } from 'i18next';

export const ITEM_I18N: Record<string, { ns: string; key: string; origin: string; dup?: boolean }> =
  {
    // ===== FISH (13) - fishes.ts =====
    fish_catfish: { ns: 'fish/species', key: 'fish_catfish', origin: 'fish' },
    fish_dragon: { ns: 'fish/species', key: 'fish_dragon', origin: 'fish' },
    fish_eel: { ns: 'fish/species', key: 'fish_eel', origin: 'fish' },
    fish_goldfish: { ns: 'fish/species', key: 'fish_goldfish', origin: 'fish' },
    fish_koi: { ns: 'fish/species', key: 'fish_koi', origin: 'fish' },
    fish_kraken: { ns: 'fish/species', key: 'fish_kraken', origin: 'fish' },
    fish_mackerel: { ns: 'fish/species', key: 'fish_mackerel', origin: 'fish' },
    fish_puffer: { ns: 'fish/species', key: 'fish_puffer', origin: 'fish' },
    fish_salmon: { ns: 'fish/species', key: 'fish_salmon', origin: 'fish' },
    fish_sardine: { ns: 'fish/species', key: 'fish_sardine', origin: 'fish' },
    fish_sword: { ns: 'fish/species', key: 'fish_sword', origin: 'fish' },
    fish_tilapia: { ns: 'fish/species', key: 'fish_tilapia', origin: 'fish' },
    fish_tuna: { ns: 'fish/species', key: 'fish_tuna', origin: 'fish' },

    // ===== EXPLORE (15) - explorations.ts =====
    ancient_relic: { ns: 'explore/items', key: 'ancient_relic', origin: 'explore' },
    bark: { ns: 'explore/items', key: 'bark', origin: 'explore' },
    chili: { ns: 'explore/items', key: 'chili', origin: 'explore' },
    gold_nugget: { ns: 'explore/items', key: 'gold_nugget', origin: 'explore' },
    herb: { ns: 'explore/items', key: 'herb', origin: 'explore' },
    iron_ore: { ns: 'explore/items', key: 'iron_ore', origin: 'explore' },
    mana_crystal: { ns: 'explore/items', key: 'mana_crystal', origin: 'explore' },
    monster_egg: { ns: 'explore/items', key: 'monster_egg', origin: 'explore' },
    moonflower: { ns: 'explore/items', key: 'moonflower', origin: 'explore' },
    mushroom: { ns: 'explore/items', key: 'mushroom', origin: 'explore' },
    mythril_ore: { ns: 'explore/items', key: 'mythril_ore', origin: 'explore' },
    stone: { ns: 'explore/items', key: 'stone', origin: 'explore' },
    string: { ns: 'explore/items', key: 'string', origin: 'explore' },
    wood: { ns: 'explore/items', key: 'wood', origin: 'explore' },
    // honey: { ns: 'explore/items', key: 'honey', origin: 'explore', dup: true }, // juga di hunt

    // ===== DUNGEON (32) - dungeon-data.ts =====
    absolute_shard: { ns: 'dungeon/items', key: 'absolute_shard', origin: 'dungeon' },
    astral_fragment: { ns: 'dungeon/items', key: 'astral_fragment', origin: 'dungeon' },
    charred_bone: { ns: 'dungeon/items', key: 'charred_bone', origin: 'dungeon' },
    dragon_heart: { ns: 'dungeon/items', key: 'dragon_heart', origin: 'dungeon' },
    drake_claw_dagger: { ns: 'dungeon/items', key: 'drake_claw_dagger', origin: 'dungeon' },
    drake_scale: { ns: 'dungeon/items', key: 'drake_scale', origin: 'dungeon' },
    ectoplasm: { ns: 'dungeon/items', key: 'ectoplasm', origin: 'dungeon' },
    frost_crystal: { ns: 'dungeon/items', key: 'frost_crystal', origin: 'dungeon' },
    golem_heart: { ns: 'dungeon/items', key: 'golem_heart', origin: 'dungeon' },
    gooey_jelly: { ns: 'dungeon/items', key: 'gooey_jelly', origin: 'dungeon' },
    heart_of_crystal: { ns: 'dungeon/items', key: 'heart_of_crystal', origin: 'dungeon' },
    ice_shard: { ns: 'dungeon/items', key: 'ice_shard', origin: 'dungeon' },
    inferno_fang: { ns: 'dungeon/items', key: 'inferno_fang', origin: 'dungeon' },
    inferno_staff: { ns: 'dungeon/items', key: 'inferno_staff', origin: 'dungeon' },
    iron_gauntlet: { ns: 'dungeon/items', key: 'iron_gauntlet', origin: 'dungeon' },
    nebula_silk: { ns: 'dungeon/items', key: 'nebula_silk', origin: 'dungeon' },
    nova_blade: { ns: 'dungeon/items', key: 'nova_blade', origin: 'dungeon' },
    nova_essence: { ns: 'dungeon/items', key: 'nova_essence', origin: 'dungeon' },
    obsidian_plate: { ns: 'dungeon/items', key: 'obsidian_plate', origin: 'dungeon' },
    quantum_orb: { ns: 'dungeon/items', key: 'quantum_orb', origin: 'dungeon' },
    reaper_scythe: { ns: 'dungeon/items', key: 'reaper_scythe', origin: 'dungeon' },
    royal_jelly: { ns: 'dungeon/items', key: 'royal_jelly', origin: 'dungeon' },
    slime_boots: { ns: 'dungeon/items', key: 'slime_boots', origin: 'dungeon' },
    slime_crown: { ns: 'dungeon/items', key: 'slime_crown', origin: 'dungeon' },
    specter_hood: { ns: 'dungeon/items', key: 'specter_hood', origin: 'dungeon' },
    star_core: { ns: 'dungeon/items', key: 'star_core', origin: 'dungeon' },
    star_dust: { ns: 'dungeon/items', key: 'star_dust', origin: 'dungeon' },
    stardust: { ns: 'dungeon/items', key: 'stardust', origin: 'dungeon' },
    stone_fragment: { ns: 'dungeon/items', key: 'stone_fragment', origin: 'dungeon' },
    warden_cape: { ns: 'dungeon/items', key: 'warden_cape', origin: 'dungeon' },
    warden_chain: { ns: 'dungeon/items', key: 'warden_chain', origin: 'dungeon' },
    // dup di hunt
    // slime_core: { ns: 'dungeon/items', key: 'slime_core', origin: 'dungeon', dup: true },
    // crystal_shard: { ns: 'dungeon/items', key: 'crystal_shard', origin: 'dungeon', dup: true },
    // void_essence: { ns: 'dungeon/items', key: 'void_essence', origin: 'dungeon', dup: true },

    // ===== HUNT (85) - monsters.ts =====
    ash_feather: { ns: 'hunt/items', key: 'ash_feather', origin: 'hunt' },
    bear_claw: { ns: 'hunt/items', key: 'bear_claw', origin: 'hunt' },
    bear_meat: { ns: 'hunt/items', key: 'bear_meat', origin: 'hunt' },
    bear_paw_gauntlet: { ns: 'hunt/items', key: 'bear_paw_gauntlet', origin: 'hunt' },
    berserk_blood: { ns: 'hunt/items', key: 'berserk_blood', origin: 'hunt' },
    berserker_armor: { ns: 'hunt/items', key: 'berserker_armor', origin: 'hunt' },
    boar_heart: { ns: 'hunt/items', key: 'boar_heart', origin: 'hunt' },
    boar_tusk_helm: { ns: 'hunt/items', key: 'boar_tusk_helm', origin: 'hunt' },
    bone: { ns: 'hunt/items', key: 'bone', origin: 'hunt' },
    bone_helm: { ns: 'hunt/items', key: 'bone_helm', origin: 'hunt' },
    claw: { ns: 'hunt/items', key: 'claw', origin: 'hunt' },
    core_lava: { ns: 'hunt/items', key: 'core_lava', origin: 'hunt' },
    crystal_staff: { ns: 'hunt/items', key: 'crystal_staff', origin: 'hunt' },
    cursed_blade: { ns: 'hunt/items', key: 'cursed_blade', origin: 'hunt' },
    dark_steel: { ns: 'hunt/items', key: 'dark_steel', origin: 'hunt' },
    desert_scale: { ns: 'hunt/items', key: 'desert_scale', origin: 'hunt' },
    desert_scale_armor: { ns: 'hunt/items', key: 'desert_scale_armor', origin: 'hunt' },
    diamond_heart: { ns: 'hunt/items', key: 'diamond_heart', origin: 'hunt' },
    eagle_talon: { ns: 'hunt/items', key: 'eagle_talon', origin: 'hunt' },
    eye_wolf: { ns: 'hunt/items', key: 'eye_wolf', origin: 'hunt' },
    fang: { ns: 'hunt/items', key: 'fang', origin: 'hunt' },
    feather: { ns: 'hunt/items', key: 'feather', origin: 'hunt' },
    fire_crystal: { ns: 'hunt/items', key: 'fire_crystal', origin: 'hunt' },
    flame_talon: { ns: 'hunt/items', key: 'flame_talon', origin: 'hunt' },
    frost_cape: { ns: 'hunt/items', key: 'frost_cape', origin: 'hunt' },
    frost_heart: { ns: 'hunt/items', key: 'frost_heart', origin: 'hunt' },
    goblin_dagger: { ns: 'hunt/items', key: 'goblin_dagger', origin: 'hunt' },
    goblin_ear: { ns: 'hunt/items', key: 'goblin_ear', origin: 'hunt' },
    golem_core: { ns: 'hunt/items', key: 'golem_core', origin: 'hunt' },
    harpy_bow: { ns: 'hunt/items', key: 'harpy_bow', origin: 'hunt' },
    harpy_egg: { ns: 'hunt/items', key: 'harpy_egg', origin: 'hunt' },
    heart_alpha: { ns: 'hunt/items', key: 'heart_alpha', origin: 'hunt' },
    hide: { ns: 'hunt/items', key: 'hide', origin: 'hunt' },
    honey: { ns: 'hunt/items', key: 'honey', origin: 'hunt', dup: true }, // juga di explore
    hydra_head: { ns: 'hunt/items', key: 'hydra_head', origin: 'hunt' },
    hydra_heart: { ns: 'hunt/items', key: 'hydra_heart', origin: 'hunt' },
    hydra_scale: { ns: 'hunt/items', key: 'hydra_scale', origin: 'hunt' },
    hydra_venom_dagger: { ns: 'hunt/items', key: 'hydra_venom_dagger', origin: 'hunt' },
    ice_club: { ns: 'hunt/items', key: 'ice_club', origin: 'hunt' },
    knight_emblem: { ns: 'hunt/items', key: 'knight_emblem', origin: 'hunt' },
    lava_boots: { ns: 'hunt/items', key: 'lava_boots', origin: 'hunt' },
    lizard_meat: { ns: 'hunt/items', key: 'lizard_meat', origin: 'hunt' },
    lizard_scale_armor: { ns: 'hunt/items', key: 'lizard_scale_armor', origin: 'hunt' },
    lizard_tail: { ns: 'hunt/items', key: 'lizard_tail', origin: 'hunt' },
    magma_jelly: { ns: 'hunt/items', key: 'magma_jelly', origin: 'hunt' },
    meat: { ns: 'hunt/items', key: 'meat', origin: 'hunt' },
    night_essence: { ns: 'hunt/items', key: 'night_essence', origin: 'hunt' },
    orc_tooth: { ns: 'hunt/items', key: 'orc_tooth', origin: 'hunt' },
    orc_warchief_helm: { ns: 'hunt/items', key: 'orc_warchief_helm', origin: 'hunt' },
    panther_heart: { ns: 'hunt/items', key: 'panther_heart', origin: 'hunt' },
    panther_pelt: { ns: 'hunt/items', key: 'panther_pelt', origin: 'hunt' },
    pelt: { ns: 'hunt/items', key: 'pelt', origin: 'hunt' },
    phoenix_tear: { ns: 'hunt/items', key: 'phoenix_tear', origin: 'hunt' },
    phoenix_wings: { ns: 'hunt/items', key: 'phoenix_wings', origin: 'hunt' },
    prism: { ns: 'hunt/items', key: 'prism', origin: 'hunt' },
    rebirth_egg: { ns: 'hunt/items', key: 'rebirth_egg', origin: 'hunt' },
    rusted_sword: { ns: 'hunt/items', key: 'rusted_sword', origin: 'hunt' },
    sand_pearl: { ns: 'hunt/items', key: 'sand_pearl', origin: 'hunt' },
    scale: { ns: 'hunt/items', key: 'scale', origin: 'hunt' },
    shadow_claw: { ns: 'hunt/items', key: 'shadow_claw', origin: 'hunt' },
    shadow_cloak: { ns: 'hunt/items', key: 'shadow_cloak', origin: 'hunt' },
    skull: { ns: 'hunt/items', key: 'skull', origin: 'hunt' },
    soul_shard: { ns: 'hunt/items', key: 'soul_shard', origin: 'hunt' },
    spider_eye: { ns: 'hunt/items', key: 'spider_eye', origin: 'hunt' },
    spider_fang: { ns: 'hunt/items', key: 'spider_fang', origin: 'hunt' },
    spider_fang_dagger: { ns: 'hunt/items', key: 'spider_fang_dagger', origin: 'hunt' },
    spider_silk: { ns: 'hunt/items', key: 'spider_silk', origin: 'hunt' },
    storm_core: { ns: 'hunt/items', key: 'storm_core', origin: 'hunt' },
    storm_feather: { ns: 'hunt/items', key: 'storm_feather', origin: 'hunt' },
    talon: { ns: 'hunt/items', key: 'talon', origin: 'hunt' },
    thunder_bow: { ns: 'hunt/items', key: 'thunder_bow', origin: 'hunt' },
    thunder_egg: { ns: 'hunt/items', key: 'thunder_egg', origin: 'hunt' },
    troll_fat: { ns: 'hunt/items', key: 'troll_fat', origin: 'hunt' },
    troll_regen: { ns: 'hunt/items', key: 'troll_regen', origin: 'hunt' },
    venom_blood: { ns: 'hunt/items', key: 'venom_blood', origin: 'hunt' },
    venom_sac: { ns: 'hunt/items', key: 'venom_sac', origin: 'hunt' },
    void_armor: { ns: 'hunt/items', key: 'void_armor', origin: 'hunt' },
    war_axe: { ns: 'hunt/items', key: 'war_axe', origin: 'hunt' },
    wind_essence: { ns: 'hunt/items', key: 'wind_essence', origin: 'hunt' },
    wolf_fang_necklace: { ns: 'hunt/items', key: 'wolf_fang_necklace', origin: 'hunt' },
    wolf_meat: { ns: 'hunt/items', key: 'wolf_meat', origin: 'hunt' },
    worm_meat: { ns: 'hunt/items', key: 'worm_meat', origin: 'hunt' },
    worm_tooth: { ns: 'hunt/items', key: 'worm_tooth', origin: 'hunt' },
    // dup di dungeon
    slime_core: { ns: 'hunt/items', key: 'slime_core', origin: 'hunt', dup: true },
    crystal_shard: { ns: 'hunt/items', key: 'crystal_shard', origin: 'hunt', dup: true },
    void_essence: { ns: 'hunt/items', key: 'void_essence', origin: 'hunt', dup: true },

    // ===== CRAFT (13) - equipments.ts sisa =====
    abyssal_rod: { ns: 'craft/items', key: 'abyssal_rod', origin: 'craft' },
    forager_bag: { ns: 'craft/items', key: 'forager_bag', origin: 'craft' },
    hunter_bow: { ns: 'craft/items', key: 'hunter_bow', origin: 'craft' },
    iron_pickaxe: { ns: 'craft/items', key: 'iron_pickaxe', origin: 'craft' },
    iron_rod: { ns: 'craft/items', key: 'iron_rod', origin: 'craft' },
    iron_sword: { ns: 'craft/items', key: 'iron_sword', origin: 'craft' },
    mage_staff: { ns: 'craft/items', key: 'mage_staff', origin: 'craft' },
    mythril_pickaxe: { ns: 'craft/items', key: 'mythril_pickaxe', origin: 'craft' },
    mythril_rod: { ns: 'craft/items', key: 'mythril_rod', origin: 'craft' },
    star_blade: { ns: 'craft/items', key: 'star_blade', origin: 'craft' },
    stone_pickaxe: { ns: 'craft/items', key: 'stone_pickaxe', origin: 'craft' },
    void_crown: { ns: 'craft/items', key: 'void_crown', origin: 'craft' },
    wooden_rod: { ns: 'craft/items', key: 'wooden_rod', origin: 'craft' },

    // ===== COOK (35) - cooking-recipes.ts =====
    bark_tea: { ns: 'cook/items', key: 'bark_tea', origin: 'cook' },
    berserk_stew: { ns: 'cook/items', key: 'berserk_stew', origin: 'cook' },
    cooked_bear: { ns: 'cook/items', key: 'cooked_bear', origin: 'cook' },
    cooked_lizard: { ns: 'cook/items', key: 'cooked_lizard', origin: 'cook' },
    cooked_mackerel: { ns: 'cook/items', key: 'cooked_mackerel', origin: 'cook' },
    cooked_meat: { ns: 'cook/items', key: 'cooked_meat', origin: 'cook' },
    cooked_salmon: { ns: 'cook/items', key: 'cooked_salmon', origin: 'cook' },
    cooked_sardine: { ns: 'cook/items', key: 'cooked_sardine', origin: 'cook' },
    cooked_tilapia: { ns: 'cook/items', key: 'cooked_tilapia', origin: 'cook' },
    cooked_tuna: { ns: 'cook/items', key: 'cooked_tuna', origin: 'cook' },
    cooked_wolf: { ns: 'cook/items', key: 'cooked_wolf', origin: 'cook' },
    crispy_harpy: { ns: 'cook/items', key: 'crispy_harpy', origin: 'cook' },
    crystal_soup: { ns: 'cook/items', key: 'crystal_soup', origin: 'cook' },
    drake_grill: { ns: 'cook/items', key: 'drake_grill', origin: 'cook' },
    ginseng_brew: { ns: 'cook/items', key: 'ginseng_brew', origin: 'cook' },
    golden_omelette: { ns: 'cook/items', key: 'golden_omelette', origin: 'cook' },
    herbal_tea: { ns: 'cook/items', key: 'herbal_tea', origin: 'cook' },
    hide_soup: { ns: 'cook/items', key: 'hide_soup', origin: 'cook' },
    hydra_gumbo: { ns: 'cook/items', key: 'hydra_gumbo', origin: 'cook' },
    knight_feast: { ns: 'cook/items', key: 'knight_feast', origin: 'cook' },
    lava_jelly: { ns: 'cook/items', key: 'lava_jelly', origin: 'cook' },
    mana_potion: { ns: 'cook/items', key: 'mana_potion', origin: 'cook' },
    moon_elixir: { ns: 'cook/items', key: 'moon_elixir', origin: 'cook' },
    mushroom_soup: { ns: 'cook/items', key: 'mushroom_soup', origin: 'cook' },
    phoenix_rebirth: { ns: 'cook/items', key: 'phoenix_rebirth', origin: 'cook' },
    shadow_curry: { ns: 'cook/items', key: 'shadow_curry', origin: 'cook' },
    silk_pie: { ns: 'cook/items', key: 'silk_pie', origin: 'cook' },
    slime_jelly: { ns: 'cook/items', key: 'slime_jelly', origin: 'cook' },
    spicy_stew: { ns: 'cook/items', key: 'spicy_stew', origin: 'cook' },
    storm_broth: { ns: 'cook/items', key: 'storm_broth', origin: 'cook' },
    troll_ragout: { ns: 'cook/items', key: 'troll_ragout', origin: 'cook' },
    venom_soup: { ns: 'cook/items', key: 'venom_soup', origin: 'cook' },
    void_soup: { ns: 'cook/items', key: 'void_soup', origin: 'cook' },
    warm_honey: { ns: 'cook/items', key: 'warm_honey', origin: 'cook' },
    worm_sushi: { ns: 'cook/items', key: 'worm_sushi', origin: 'cook' },

    // ===== SHOP (4) - crafting-recipes.ts sisa =====
    drake_claw: { ns: 'shop/items', key: 'drake_claw', origin: 'shop' },
    root: { ns: 'shop/items', key: 'root', origin: 'shop' },
    silk: { ns: 'shop/items', key: 'silk', origin: 'shop' },
    soul_wisp: { ns: 'shop/items', key: 'soul_wisp', origin: 'shop' },
  };

export async function getItemDisplay(itemId: string, t: TFunction) {
  const entry = ITEM_I18N[itemId];
  if (!entry) return null;

  const [domain, category] = entry.ns.split('/') as [any, any];

  let name: string;
  let desc: string = '';

  if (domain === 'fish') {
    name = i18nFish(itemId, t);
    desc = i18nFishDesc(itemId, t);
  } else {
    name = i18nItem(domain as any, itemId, t);
    desc = i18nItemDesc(domain as any, itemId, t);
  }
  return { name, description: desc };
}
