import { i18nItem, i18nItemDesc, i18nFish, i18nFishDesc } from '../i18n/display.ts';
import type { TFunction } from 'i18next';

export const ITEM_I18N: Record<string, { ns: string; origin: string; dup?: boolean }> = {
  // ===== FISH (13) - fishes.ts =====
  fish_catfish: { ns: 'fish/species', origin: 'fish' },
  fish_dragon: { ns: 'fish/species', origin: 'fish' },
  fish_eel: { ns: 'fish/species', origin: 'fish' },
  fish_goldfish: { ns: 'fish/species', origin: 'fish' },
  fish_koi: { ns: 'fish/species', origin: 'fish' },
  fish_kraken: { ns: 'fish/species', origin: 'fish' },
  fish_mackerel: { ns: 'fish/species', origin: 'fish' },
  fish_puffer: { ns: 'fish/species', origin: 'fish' },
  fish_salmon: { ns: 'fish/species', origin: 'fish' },
  fish_sardine: { ns: 'fish/species', origin: 'fish' },
  fish_sword: { ns: 'fish/species', origin: 'fish' },
  fish_tilapia: { ns: 'fish/species', origin: 'fish' },
  fish_tuna: { ns: 'fish/species', origin: 'fish' },

  // ===== EXPLORE (15) - explorations.ts =====
  ancient_relic: { ns: 'explore/items', origin: 'explore' },
  bark: { ns: 'explore/items', origin: 'explore' },
  chili: { ns: 'explore/items', origin: 'explore' },
  gold_nugget: { ns: 'explore/items', origin: 'explore' },
  herb: { ns: 'explore/items', origin: 'explore' },
  iron_ore: { ns: 'explore/items', origin: 'explore' },
  mana_crystal: { ns: 'explore/items', origin: 'explore' },
  monster_egg: { ns: 'explore/items', origin: 'explore' },
  moonflower: { ns: 'explore/items', origin: 'explore' },
  mushroom: { ns: 'explore/items', origin: 'explore' },
  mythril_ore: { ns: 'explore/items', origin: 'explore' },
  stone: { ns: 'explore/items', origin: 'explore' },
  string: { ns: 'explore/items', origin: 'explore' },
  wood: { ns: 'explore/items', origin: 'explore' },

  // honey: { ns: 'explore/items', origin: 'explore', dup: true }, // juga di hunt

  // ===== DUNGEON (32) - dungeon-data.ts =====
  absolute_shard: { ns: 'dungeon/items', origin: 'dungeon' },
  astral_fragment: { ns: 'dungeon/items', origin: 'dungeon' },
  charred_bone: { ns: 'dungeon/items', origin: 'dungeon' },
  dragon_heart: { ns: 'dungeon/items', origin: 'dungeon' },
  drake_claw_dagger: { ns: 'dungeon/items', origin: 'dungeon' },
  drake_scale: { ns: 'dungeon/items', origin: 'dungeon' },
  ectoplasm: { ns: 'dungeon/items', origin: 'dungeon' },
  frost_crystal: { ns: 'dungeon/items', origin: 'dungeon' },
  golem_heart: { ns: 'dungeon/items', origin: 'dungeon' },
  gooey_jelly: { ns: 'dungeon/items', origin: 'dungeon' },
  heart_of_crystal: { ns: 'dungeon/items', origin: 'dungeon' },
  ice_shard: { ns: 'dungeon/items', origin: 'dungeon' },
  inferno_fang: { ns: 'dungeon/items', origin: 'dungeon' },
  inferno_staff: { ns: 'dungeon/items', origin: 'dungeon' },
  iron_gauntlet: { ns: 'dungeon/items', origin: 'dungeon' },
  nebula_silk: { ns: 'dungeon/items', origin: 'dungeon' },
  nova_blade: { ns: 'dungeon/items', origin: 'dungeon' },
  nova_essence: { ns: 'dungeon/items', origin: 'dungeon' },
  obsidian_plate: { ns: 'dungeon/items', origin: 'dungeon' },
  quantum_orb: { ns: 'dungeon/items', origin: 'dungeon' },
  reaper_scythe: { ns: 'dungeon/items', origin: 'dungeon' },
  royal_jelly: { ns: 'dungeon/items', origin: 'dungeon' },
  slime_boots: { ns: 'dungeon/items', origin: 'dungeon' },
  slime_crown: { ns: 'dungeon/items', origin: 'dungeon' },
  specter_hood: { ns: 'dungeon/items', origin: 'dungeon' },
  star_core: { ns: 'dungeon/items', origin: 'dungeon' },
  star_dust: { ns: 'dungeon/items', origin: 'dungeon' },
  stardust: { ns: 'dungeon/items', origin: 'dungeon' },
  stone_fragment: { ns: 'dungeon/items', origin: 'dungeon' },
  warden_cape: { ns: 'dungeon/items', origin: 'dungeon' },
  warden_chain: { ns: 'dungeon/items', origin: 'dungeon' },
  star_blade: { ns: 'dungeon/items', origin: 'craft' },
  void_crown: { ns: 'dungeon/items', origin: 'craft' },

  // dup di hunt
  // slime_core: { ns: 'dungeon/items', origin: 'dungeon', dup: true },
  // crystal_shard: { ns: 'dungeon/items', origin: 'dungeon', dup: true },
  // void_essence: { ns: 'dungeon/items', origin: 'dungeon', dup: true },

  // ===== HUNT (85) - monsters.ts =====
  ash_feather: { ns: 'hunt/items', origin: 'hunt' },
  bear_claw: { ns: 'hunt/items', origin: 'hunt' },
  bear_meat: { ns: 'hunt/items', origin: 'hunt' },
  bear_paw_gauntlet: { ns: 'hunt/items', origin: 'hunt' },
  berserk_blood: { ns: 'hunt/items', origin: 'hunt' },
  berserker_armor: { ns: 'hunt/items', origin: 'hunt' },
  boar_heart: { ns: 'hunt/items', origin: 'hunt' },
  boar_tusk_helm: { ns: 'hunt/items', origin: 'hunt' },
  bone: { ns: 'hunt/items', origin: 'hunt' },
  bone_helm: { ns: 'hunt/items', origin: 'hunt' },
  claw: { ns: 'hunt/items', origin: 'hunt' },
  core_lava: { ns: 'hunt/items', origin: 'hunt' },
  crystal_staff: { ns: 'hunt/items', origin: 'hunt' },
  cursed_blade: { ns: 'hunt/items', origin: 'hunt' },
  dark_steel: { ns: 'hunt/items', origin: 'hunt' },
  desert_scale: { ns: 'hunt/items', origin: 'hunt' },
  desert_scale_armor: { ns: 'hunt/items', origin: 'hunt' },
  diamond_heart: { ns: 'hunt/items', origin: 'hunt' },
  eagle_talon: { ns: 'hunt/items', origin: 'hunt' },
  eye_wolf: { ns: 'hunt/items', origin: 'hunt' },
  fang: { ns: 'hunt/items', origin: 'hunt' },
  feather: { ns: 'hunt/items', origin: 'hunt' },
  fire_crystal: { ns: 'hunt/items', origin: 'hunt' },
  flame_talon: { ns: 'hunt/items', origin: 'hunt' },
  frost_cape: { ns: 'hunt/items', origin: 'hunt' },
  frost_heart: { ns: 'hunt/items', origin: 'hunt' },
  goblin_dagger: { ns: 'hunt/items', origin: 'hunt' },
  goblin_ear: { ns: 'hunt/items', origin: 'hunt' },
  golem_core: { ns: 'hunt/items', origin: 'hunt' },
  harpy_bow: { ns: 'hunt/items', origin: 'hunt' },
  harpy_egg: { ns: 'hunt/items', origin: 'hunt' },
  heart_alpha: { ns: 'hunt/items', origin: 'hunt' },
  hide: { ns: 'hunt/items', origin: 'hunt' },
  honey: { ns: 'hunt/items', origin: 'hunt', dup: true }, // juga di explore
  hydra_head: { ns: 'hunt/items', origin: 'hunt' },
  hydra_heart: { ns: 'hunt/items', origin: 'hunt' },
  hydra_scale: { ns: 'hunt/items', origin: 'hunt' },
  hydra_venom_dagger: { ns: 'hunt/items', origin: 'hunt' },
  ice_club: { ns: 'hunt/items', origin: 'hunt' },
  knight_emblem: { ns: 'hunt/items', origin: 'hunt' },
  lava_boots: { ns: 'hunt/items', origin: 'hunt' },
  lizard_meat: { ns: 'hunt/items', origin: 'hunt' },
  lizard_scale_armor: { ns: 'hunt/items', origin: 'hunt' },
  lizard_tail: { ns: 'hunt/items', origin: 'hunt' },
  magma_jelly: { ns: 'hunt/items', origin: 'hunt' },
  meat: { ns: 'hunt/items', origin: 'hunt' },
  night_essence: { ns: 'hunt/items', origin: 'hunt' },
  orc_tooth: { ns: 'hunt/items', origin: 'hunt' },
  orc_warchief_helm: { ns: 'hunt/items', origin: 'hunt' },
  panther_heart: { ns: 'hunt/items', origin: 'hunt' },
  panther_pelt: { ns: 'hunt/items', origin: 'hunt' },
  pelt: { ns: 'hunt/items', origin: 'hunt' },
  phoenix_tear: { ns: 'hunt/items', origin: 'hunt' },
  phoenix_wings: { ns: 'hunt/items', origin: 'hunt' },
  prism: { ns: 'hunt/items', origin: 'hunt' },
  rebirth_egg: { ns: 'hunt/items', origin: 'hunt' },
  rusted_sword: { ns: 'hunt/items', origin: 'hunt' },
  sand_pearl: { ns: 'hunt/items', origin: 'hunt' },
  scale: { ns: 'hunt/items', origin: 'hunt' },
  shadow_claw: { ns: 'hunt/items', origin: 'hunt' },
  shadow_cloak: { ns: 'hunt/items', origin: 'hunt' },
  skull: { ns: 'hunt/items', origin: 'hunt' },
  soul_shard: { ns: 'hunt/items', origin: 'hunt' },
  spider_eye: { ns: 'hunt/items', origin: 'hunt' },
  spider_fang: { ns: 'hunt/items', origin: 'hunt' },
  spider_fang_dagger: { ns: 'hunt/items', origin: 'hunt' },
  spider_silk: { ns: 'hunt/items', origin: 'hunt' },
  storm_core: { ns: 'hunt/items', origin: 'hunt' },
  storm_feather: { ns: 'hunt/items', origin: 'hunt' },
  talon: { ns: 'hunt/items', origin: 'hunt' },
  thunder_bow: { ns: 'hunt/items', origin: 'hunt' },
  thunder_egg: { ns: 'hunt/items', origin: 'hunt' },
  troll_fat: { ns: 'hunt/items', origin: 'hunt' },
  troll_regen: { ns: 'hunt/items', origin: 'hunt' },
  venom_blood: { ns: 'hunt/items', origin: 'hunt' },
  venom_sac: { ns: 'hunt/items', origin: 'hunt' },
  void_armor: { ns: 'hunt/items', origin: 'hunt' },
  war_axe: { ns: 'hunt/items', origin: 'hunt' },
  wind_essence: { ns: 'hunt/items', origin: 'hunt' },
  wolf_fang_necklace: { ns: 'hunt/items', origin: 'hunt' },
  wolf_meat: { ns: 'hunt/items', origin: 'hunt' },
  worm_meat: { ns: 'hunt/items', origin: 'hunt' },
  worm_tooth: { ns: 'hunt/items', origin: 'hunt' },

  // dup di dungeon
  slime_core: { ns: 'hunt/items', origin: 'hunt', dup: true },
  crystal_shard: { ns: 'hunt/items', origin: 'hunt', dup: true },
  void_essence: { ns: 'hunt/items', origin: 'hunt', dup: true },

  // ===== CRAFT (13) - equipments.ts sisa =====
  abyssal_rod: { ns: 'craft/items', origin: 'craft' },
  forager_bag: { ns: 'craft/items', origin: 'craft' },
  hunter_bow: { ns: 'craft/items', origin: 'craft' },
  iron_pickaxe: { ns: 'craft/items', origin: 'craft' },
  iron_rod: { ns: 'craft/items', origin: 'craft' },
  iron_sword: { ns: 'craft/items', origin: 'craft' },
  mage_staff: { ns: 'craft/items', origin: 'craft' },
  mythril_pickaxe: { ns: 'craft/items', origin: 'craft' },
  mythril_rod: { ns: 'craft/items', origin: 'craft' },
  stone_pickaxe: { ns: 'craft/items', origin: 'craft' },
  wooden_rod: { ns: 'craft/items', origin: 'craft' },

  // ===== COOK (35) - cooking-recipes.ts =====
  bark_tea: { ns: 'cook/items', origin: 'cook' },
  berserk_stew: { ns: 'cook/items', origin: 'cook' },
  cooked_bear: { ns: 'cook/items', origin: 'cook' },
  cooked_lizard: { ns: 'cook/items', origin: 'cook' },
  cooked_mackerel: { ns: 'cook/items', origin: 'cook' },
  cooked_meat: { ns: 'cook/items', origin: 'cook' },
  cooked_salmon: { ns: 'cook/items', origin: 'cook' },
  cooked_sardine: { ns: 'cook/items', origin: 'cook' },
  cooked_tilapia: { ns: 'cook/items', origin: 'cook' },
  cooked_tuna: { ns: 'cook/items', origin: 'cook' },
  cooked_wolf: { ns: 'cook/items', origin: 'cook' },
  crispy_harpy: { ns: 'cook/items', origin: 'cook' },
  crystal_soup: { ns: 'cook/items', origin: 'cook' },
  drake_grill: { ns: 'cook/items', origin: 'cook' },
  ginseng_brew: { ns: 'cook/items', origin: 'cook' },
  golden_omelette: { ns: 'cook/items', origin: 'cook' },
  herbal_tea: { ns: 'cook/items', origin: 'cook' },
  hide_soup: { ns: 'cook/items', origin: 'cook' },
  hydra_gumbo: { ns: 'cook/items', origin: 'cook' },
  knight_feast: { ns: 'cook/items', origin: 'cook' },
  lava_jelly: { ns: 'cook/items', origin: 'cook' },
  mana_potion: { ns: 'cook/items', origin: 'cook' },
  moon_elixir: { ns: 'cook/items', origin: 'cook' },
  mushroom_soup: { ns: 'cook/items', origin: 'cook' },
  phoenix_rebirth: { ns: 'cook/items', origin: 'cook' },
  shadow_curry: { ns: 'cook/items', origin: 'cook' },
  silk_pie: { ns: 'cook/items', origin: 'cook' },
  slime_jelly: { ns: 'cook/items', origin: 'cook' },
  spicy_stew: { ns: 'cook/items', origin: 'cook' },
  storm_broth: { ns: 'cook/items', origin: 'cook' },
  troll_ragout: { ns: 'cook/items', origin: 'cook' },
  venom_soup: { ns: 'cook/items', origin: 'cook' },
  void_soup: { ns: 'cook/items', origin: 'cook' },
  warm_honey: { ns: 'cook/items', origin: 'cook' },
  worm_sushi: { ns: 'cook/items', origin: 'cook' },

  // ===== SHOP (4) - crafting-recipes.ts sisa =====
  drake_claw: { ns: 'shop/items', origin: 'shop' },
  root: { ns: 'shop/items', origin: 'shop' },
  silk: { ns: 'shop/items', origin: 'shop' },
  soul_wisp: { ns: 'shop/items', origin: 'shop' },
};

export async function getItemDisplay(itemId: string, t: TFunction) {
  const entry = ITEM_I18N[itemId];
  if (!entry) return null;

  const [domain] = entry.ns.split('/') as [any];

  if (domain === 'fish') {
    return {
      name: i18nFish(itemId, t),
      description: i18nFishDesc(itemId, t),
    };
  }

  return {
    name: i18nItem(domain as any, itemId, t),
    description: i18nItemDesc(domain as any, itemId, t),
  };
}
