import type { Rarity } from '../utils';
import type { EquipmentSlot, IEquipmentStat, IItemEffect } from '@nova/db';
import { EQUIPMENTS } from './equipments';

export interface Drop {
  id: string;
  emoji: string;
  rarity: Rarity;
  chance: number;
  sellPrice: number;
  type: 'material' | 'equipment' | 'consumable';
  slot?: EquipmentSlot;
  effects?: IItemEffect[];
  stats?: IEquipmentStat;
}
export interface BaseMonster {
  id: string;
  emoji: string;
  hp: number;
  dmg: [number, number];
  minLevel: number;
  xp: number;
  drops: Drop[];
  level?: number;
}

export const BASE_MONSTERS: BaseMonster[] = [
  {
    id: 'wild_boar',
    emoji: '🐗',
    hp: 60,
    dmg: [8, 15],
    minLevel: 1,
    xp: 18,
    drops: [
      { id: 'meat', emoji: '🥩', rarity: 'Common', chance: 60, sellPrice: 12, type: 'material' },
      { ...EQUIPMENTS.boar_tusk_helm, chance: 3 },
      { id: 'fang', emoji: '🦷', rarity: 'Uncommon', chance: 27, sellPrice: 28, type: 'material' },
      {
        id: 'boar_heart',
        emoji: '❤️',
        rarity: 'Rare',
        chance: 10,
        sellPrice: 75,
        type: 'material',
      },
    ],
  },
  {
    id: 'goblin_scout',
    emoji: '👺',
    hp: 50,
    dmg: [5, 12],
    minLevel: 1,
    xp: 15,
    drops: [
      {
        id: 'goblin_ear',
        emoji: '👂',
        rarity: 'Common',
        chance: 55,
        sellPrice: 10,
        type: 'material',
      },
      { id: 'hide', emoji: '🦌', rarity: 'Common', chance: 30, sellPrice: 12, type: 'material' },
      { ...EQUIPMENTS.goblin_dagger, chance: 15 },
    ],
  },
  {
    id: 'swamp_lizard',
    emoji: '🦎',
    hp: 70,
    dmg: [10, 18],
    minLevel: 2,
    xp: 22,
    drops: [
      {
        id: 'lizard_meat',
        emoji: '🍗',
        rarity: 'Common',
        chance: 57,
        sellPrice: 14,
        type: 'material',
      },
      { ...EQUIPMENTS.lizard_scale_armor, chance: 3 },
      {
        id: 'lizard_tail',
        emoji: '🦎',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 26,
        type: 'material',
      },
      { id: 'scale', emoji: '🟢', rarity: 'Rare', chance: 10, sellPrice: 60, type: 'material' },
    ],
  },
  {
    id: 'forest_wolf',
    emoji: '🐺',
    hp: 80,
    dmg: [12, 20],
    minLevel: 3,
    xp: 28,
    drops: [
      {
        id: 'wolf_meat',
        emoji: '🍖',
        rarity: 'Common',
        chance: 50,
        sellPrice: 15,
        type: 'material',
      },
      { ...EQUIPMENTS.wolf_fang_necklace, chance: 3 },
      { id: 'claw', emoji: '🐾', rarity: 'Uncommon', chance: 32, sellPrice: 25, type: 'material' },
      { id: 'pelt', emoji: '🧶', rarity: 'Rare', chance: 5, sellPrice: 55, type: 'material' },
      { id: 'eye_wolf', emoji: '👁️', rarity: 'Epic', chance: 10, sellPrice: 180, type: 'material' },
    ],
  },
  {
    id: 'cave_bear',
    emoji: '🐻',
    hp: 120,
    dmg: [18, 28],
    minLevel: 5,
    xp: 45,
    drops: [
      {
        id: 'bear_meat',
        emoji: '🥩',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 35,
        type: 'material',
      },
      { ...EQUIPMENTS.bear_paw_gauntlet, chance: 3 },
      {
        id: 'honey',
        emoji: '🍯',
        rarity: 'Uncommon',
        chance: 15,
        sellPrice: 30,
        type: 'consumable',
        effects: [{ type: 'heal', value: 25 }],
      },
      { id: 'bear_claw', emoji: '🐾', rarity: 'Rare', chance: 30, sellPrice: 80, type: 'material' },
      {
        id: 'heart_alpha',
        emoji: '❤️‍🔥',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 400,
        type: 'consumable',
        effects: [{ type: 'heal', value: 60 }],
      },
    ],
  },
  {
    id: 'skeleton_warrior',
    emoji: '💀',
    hp: 110,
    dmg: [16, 26],
    minLevel: 5,
    xp: 42,
    drops: [
      { id: 'bone', emoji: '🦴', rarity: 'Common', chance: 52, sellPrice: 18, type: 'material' },
      { ...EQUIPMENTS.rusted_sword, chance: 30 },
      { ...EQUIPMENTS.bone_helm, chance: 3 },
      { id: 'skull', emoji: '💀', rarity: 'Rare', chance: 12, sellPrice: 95, type: 'material' },
      {
        id: 'soul_shard',
        emoji: '🔮',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 220,
        type: 'material',
      },
    ],
  },
  {
    id: 'venom_spider',
    emoji: '🕷️',
    hp: 95,
    dmg: [14, 24],
    minLevel: 6,
    xp: 48,
    drops: [
      {
        id: 'spider_silk',
        emoji: '🕸️',
        rarity: 'Common',
        chance: 50,
        sellPrice: 22,
        type: 'material',
      },
      { ...EQUIPMENTS.spider_fang_dagger, chance: 3 },
      {
        id: 'venom_sac',
        emoji: '🧪',
        rarity: 'Uncommon',
        chance: 32,
        sellPrice: 55,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 20 }],
      },
      {
        id: 'spider_fang',
        emoji: '🦷',
        rarity: 'Rare',
        chance: 12,
        sellPrice: 110,
        type: 'material',
      },
      {
        id: 'spider_eye',
        emoji: '👁️',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 250,
        type: 'material',
      },
    ],
  },
  {
    id: 'harpy',
    emoji: '🦅',
    hp: 105,
    dmg: [17, 27],
    minLevel: 7,
    xp: 52,
    drops: [
      { id: 'feather', emoji: '🪶', rarity: 'Common', chance: 52, sellPrice: 20, type: 'material' },
      { ...EQUIPMENTS.harpy_bow, chance: 3 },
      { id: 'talon', emoji: '🦅', rarity: 'Uncommon', chance: 30, sellPrice: 60, type: 'material' },
      {
        id: 'wind_essence',
        emoji: '💨',
        rarity: 'Rare',
        chance: 12,
        sellPrice: 130,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 25 }],
      },
      {
        id: 'harpy_egg',
        emoji: '🥚',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 280,
        type: 'consumable',
        effects: [{ type: 'heal', value: 45 }],
      },
    ],
  },
  {
    id: 'orc_berserker',
    emoji: '👹',
    hp: 140,
    dmg: [20, 32],
    minLevel: 8,
    xp: 60,
    drops: [
      {
        id: 'orc_tooth',
        emoji: '🦷',
        rarity: 'Common',
        chance: 47,
        sellPrice: 25,
        type: 'material',
      },
      { ...EQUIPMENTS.war_axe, chance: 30 },
      { ...EQUIPMENTS.berserker_armor, chance: 3 },
      {
        id: 'berserk_blood',
        emoji: '🩸',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 140,
        type: 'consumable',
        effects: [{ type: 'buff', value: 15 }],
      },
      { ...EQUIPMENTS.orc_warchief_helm, chance: 5 },
    ],
  },
  {
    id: 'shadow_panther',
    emoji: '🐆',
    hp: 130,
    dmg: [22, 34],
    minLevel: 9,
    xp: 65,
    drops: [
      {
        id: 'panther_pelt',
        emoji: '🖤',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 65,
        type: 'material',
      },
      { ...EQUIPMENTS.shadow_cloak, chance: 3 },
      {
        id: 'shadow_claw',
        emoji: '🐾',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 125,
        type: 'material',
      },
      {
        id: 'night_essence',
        emoji: '🌑',
        rarity: 'Epic',
        chance: 15,
        sellPrice: 260,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 30 }],
      },
      {
        id: 'panther_heart',
        emoji: '🖤',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 580,
        type: 'consumable',
        effects: [{ type: 'heal', value: 70 }],
      },
    ],
  },
  {
    id: 'lava_slime',
    emoji: '🟠',
    hp: 150,
    dmg: [18, 30],
    minLevel: 10,
    xp: 70,
    drops: [
      {
        id: 'slime_core',
        emoji: '🧡',
        rarity: 'Common',
        chance: 42,
        sellPrice: 30,
        type: 'material',
      },
      { ...EQUIPMENTS.lava_boots, chance: 3 },
      {
        id: 'magma_jelly',
        emoji: '🍮',
        rarity: 'Uncommon',
        chance: 35,
        sellPrice: 75,
        type: 'consumable',
        effects: [{ type: 'heal', value: 35 }],
      },
      {
        id: 'fire_crystal',
        emoji: '🔥',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 160,
        type: 'material',
      },
      {
        id: 'core_lava',
        emoji: '❤️‍🔥',
        rarity: 'Epic',
        chance: 5,
        sellPrice: 320,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 40 }],
      },
    ],
  },
  {
    id: 'frost_troll',
    emoji: '🧌',
    hp: 180,
    dmg: [24, 36],
    minLevel: 12,
    xp: 85,
    drops: [
      {
        id: 'troll_fat',
        emoji: '🧈',
        rarity: 'Common',
        chance: 42,
        sellPrice: 40,
        type: 'material',
      },
      { ...EQUIPMENTS.ice_club, chance: 30 },
      { ...EQUIPMENTS.frost_cape, chance: 3 },
      {
        id: 'frost_heart',
        emoji: '💙',
        rarity: 'Rare',
        chance: 18,
        sellPrice: 190,
        type: 'consumable',
        effects: [{ type: 'heal', value: 50 }],
      },
      {
        id: 'troll_regen',
        emoji: '💧',
        rarity: 'Epic',
        chance: 7,
        sellPrice: 380,
        type: 'consumable',
        effects: [{ type: 'heal', value: 90 }],
      },
    ],
  },
  {
    id: 'sand_worm',
    emoji: '🪱',
    hp: 200,
    dmg: [26, 40],
    minLevel: 14,
    xp: 95,
    drops: [
      {
        id: 'worm_meat',
        emoji: '🥩',
        rarity: 'Common',
        chance: 47,
        sellPrice: 45,
        type: 'consumable',
        effects: [{ type: 'heal', value: 30 }],
      },
      {
        id: 'sand_pearl',
        emoji: '⚪',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 110,
        type: 'material',
      },
      { ...EQUIPMENTS.desert_scale_armor, chance: 3 },
      {
        id: 'desert_scale',
        emoji: '🏜️',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 210,
        type: 'material',
      },
      {
        id: 'worm_tooth',
        emoji: '🦷',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 650,
        type: 'material',
      },
    ],
  },
  {
    id: 'dark_knight',
    emoji: '🗡️',
    hp: 220,
    dmg: [28, 42],
    minLevel: 15,
    xp: 105,
    drops: [
      {
        id: 'dark_steel',
        emoji: '⚫',
        rarity: 'Uncommon',
        chance: 42,
        sellPrice: 120,
        type: 'material',
      },
      { ...EQUIPMENTS.cursed_blade, chance: 30 },
      { ...EQUIPMENTS.void_armor, chance: 3 },
      {
        id: 'knight_emblem',
        emoji: '🛡️',
        rarity: 'Epic',
        chance: 20,
        sellPrice: 420,
        type: 'material',
      },
      {
        id: 'void_essence',
        emoji: '🕳️',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 780,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 50 }],
      },
    ],
  },
  {
    id: 'thunder_eagle',
    emoji: '⚡',
    hp: 190,
    dmg: [30, 45],
    minLevel: 17,
    xp: 115,
    drops: [
      {
        id: 'storm_feather',
        emoji: '🪶',
        rarity: 'Uncommon',
        chance: 42,
        sellPrice: 130,
        type: 'material',
      },
      {
        id: 'eagle_talon',
        emoji: '⚡',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 250,
        type: 'material',
      },
      { ...EQUIPMENTS.thunder_bow, chance: 3 },
      {
        id: 'thunder_egg',
        emoji: '🥚',
        rarity: 'Epic',
        chance: 20,
        sellPrice: 460,
        type: 'consumable',
        effects: [{ type: 'heal', value: 80 }],
      },
      {
        id: 'storm_core',
        emoji: '🌩️',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 1200,
        type: 'consumable',
        effects: [{ type: 'stamina', value: 70 }],
      },
    ],
  },
  {
    id: 'crystal_golem',
    emoji: '💎',
    hp: 260,
    dmg: [25, 38],
    minLevel: 19,
    xp: 130,
    drops: [
      {
        id: 'crystal_shard',
        emoji: '🔹',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 140,
        type: 'material',
      },
      {
        id: 'golem_core',
        emoji: '🔷',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 280,
        type: 'material',
      },
      { ...EQUIPMENTS.crystal_staff, chance: 3 },
      { id: 'prism', emoji: '✨', rarity: 'Epic', chance: 15, sellPrice: 520, type: 'material' },
      {
        id: 'diamond_heart',
        emoji: '💠',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 1500,
        type: 'consumable',
        effects: [{ type: 'heal', value: 150 }],
      },
    ],
  },
  {
    id: 'hydra',
    emoji: '🐉',
    hp: 320,
    dmg: [32, 48],
    minLevel: 22,
    xp: 160,
    drops: [
      {
        id: 'hydra_scale',
        emoji: '🐍',
        rarity: 'Rare',
        chance: 37,
        sellPrice: 300,
        type: 'material',
      },
      {
        id: 'hydra_head',
        emoji: '🐉',
        rarity: 'Epic',
        chance: 35,
        sellPrice: 580,
        type: 'material',
      },
      { ...EQUIPMENTS.hydra_venom_dagger, chance: 3 },
      {
        id: 'venom_blood',
        emoji: '☠️',
        rarity: 'Legendary',
        chance: 20,
        sellPrice: 950,
        type: 'consumable',
        effects: [{ type: 'buff', value: 25 }],
      },
      {
        id: 'hydra_heart',
        emoji: '💚',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 2100,
        type: 'consumable',
        effects: [{ type: 'heal', value: 200 }],
      },
    ],
  },
  {
    id: 'phoenix',
    emoji: '🔥',
    hp: 300,
    dmg: [35, 52],
    minLevel: 25,
    xp: 185,
    drops: [
      {
        id: 'ash_feather',
        emoji: '🪶',
        rarity: 'Rare',
        chance: 37,
        sellPrice: 340,
        type: 'material',
      },
      {
        id: 'flame_talon',
        emoji: '🔥',
        rarity: 'Epic',
        chance: 35,
        sellPrice: 650,
        type: 'material',
      },
      { ...EQUIPMENTS.phoenix_wings, chance: 3 },
      {
        id: 'phoenix_tear',
        emoji: '💧',
        rarity: 'Legendary',
        chance: 20,
        sellPrice: 1100,
        type: 'consumable',
        effects: [
          { type: 'heal', value: 180 },
          { type: 'stamina', value: 50 },
        ],
      },
      {
        id: 'rebirth_egg',
        emoji: '🥚',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 2500,
        type: 'consumable',
        effects: [
          { type: 'stamina', value: 100 },
          { type: 'heal', value: 50 },
        ],
      },
    ],
  },
];

export const getScaledMonster = (userLevel: number) => {
  const available = BASE_MONSTERS.filter((m) => userLevel >= m.minLevel);
  const base = available[Math.floor(Math.random() * available.length)];
  const diff = userLevel - base.minLevel;
  const hpScale = 1 + diff * 0.12;
  const dmgScale = 1 + diff * 0.08;
  return {
    ...base,
    hp: Math.floor(base.hp * hpScale),
    dmg: [Math.floor(base.dmg[0] * dmgScale), Math.floor(base.dmg[1] * dmgScale)] as [
      number,
      number,
    ],
    xp: Math.floor(base.xp * hpScale),
    level: userLevel,
  };
};
