import type { Rarity } from '../utils';

export interface Drop {
  id: string;
  name: string;
  emoji: string;
  rarity: Rarity;
  chance: number;
  sellPrice: number;
  type: 'material' | 'equipment' | 'consumable';
  description: string;
  effects?: { type: 'heal' | 'stamina' | 'mana' | 'buff'; value: number }[];
  stats?: { atk?: number; def?: number; hp?: number; critRate?: number; critDmg?: number };
  classLock?: ('warrior' | 'mage' | 'rogue')[];
}

export interface BaseMonster {
  name: string;
  emoji: string;
  hp: number;
  dmg: [number, number];
  minLevel: number;
  xp: number;
  drops: Drop[];
  level?: number;
}

export const BASE_MONSTERS: BaseMonster[] = [
  {
    name: 'Wild Boar',
    emoji: '🐗',
    hp: 60,
    dmg: [8, 15],
    minLevel: 1,
    xp: 18,
    drops: [
      {
        id: 'meat',
        name: 'Daging Babi',
        emoji: '🥩',
        rarity: 'Common',
        chance: 60,
        sellPrice: 12,
        type: 'material',
        description: 'Daging merah, bahan dasar steak',
      },
      {
        id: 'boar_tusk_helm',
        name: 'Helm Taring Babi',
        emoji: '🐗⛑️',
        rarity: 'Uncommon',
        chance: 3,
        sellPrice: 80,
        type: 'equipment',
        description: 'Helm dari taring babi. +HP',
        stats: { hp: 15, def: 1 },
      },
      {
        id: 'fang',
        name: 'Taring Babi',
        emoji: '🦷',
        rarity: 'Uncommon',
        chance: 27,
        sellPrice: 28,
        type: 'material',
        description: 'Taring tajam untuk kerajinan',
      },
      {
        id: 'boar_heart',
        name: 'Jantung Babi',
        emoji: '❤️',
        rarity: 'Rare',
        chance: 10,
        sellPrice: 75,
        type: 'material',
        description: 'Jantung berotot, dipercaya tambah stamina',
      },
    ],
  },
  {
    name: 'Goblin Scout',
    emoji: '👺',
    hp: 50,
    dmg: [5, 12],
    minLevel: 1,
    xp: 15,
    drops: [
      {
        id: 'goblin_ear',
        name: 'Telinga Goblin',
        emoji: '👂',
        rarity: 'Common',
        chance: 55,
        sellPrice: 10,
        type: 'material',
        description: 'Bukti buruan goblin',
      },
      {
        id: 'hide',
        name: 'Kulit Goblin',
        emoji: '🦌',
        rarity: 'Common',
        chance: 30,
        sellPrice: 12,
        type: 'material',
        description: 'Kulit kasar, bisa untuk sup',
      },
      {
        id: 'goblin_dagger',
        name: 'Belati Karat',
        emoji: '🗡️',
        rarity: 'Uncommon',
        chance: 15,
        sellPrice: 40,
        type: 'equipment',
        description: 'Belati curian, masih bisa dipakai',
        stats: { atk: 6, critRate: 0.03 },
        classLock: ['rogue'],
      },
    ],
  },
  {
    name: 'Swamp Lizard',
    emoji: '🦎',
    hp: 70,
    dmg: [10, 18],
    minLevel: 2,
    xp: 22,
    drops: [
      {
        id: 'lizard_meat',
        name: 'Daging Kadal',
        emoji: '🍗',
        rarity: 'Common',
        chance: 57,
        sellPrice: 14,
        type: 'material',
        description: 'Daging rawa, cocok disate',
      },
      {
        id: 'lizard_scale_armor',
        name: 'Armor Sisik Kadal',
        emoji: '🦎🛡️',
        rarity: 'Uncommon',
        chance: 3,
        sellPrice: 90,
        type: 'equipment',
        description: 'Armor ringan dari sisik kadal. +HP +DEF',
        stats: { hp: 12, def: 2 },
      },
      {
        id: 'lizard_tail',
        name: 'Ekor Kadal',
        emoji: '🦎',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 26,
        type: 'material',
        description: 'Ekor yang bisa tumbuh lagi',
      },
      {
        id: 'scale',
        name: 'Sisik Hijau',
        emoji: '🟢',
        rarity: 'Rare',
        chance: 10,
        sellPrice: 60,
        type: 'material',
        description: 'Sisik mengkilap dari rawa',
      },
    ],
  },
  {
    name: 'Forest Wolf',
    emoji: '🐺',
    hp: 80,
    dmg: [12, 20],
    minLevel: 3,
    xp: 28,
    drops: [
      {
        id: 'wolf_meat',
        name: 'Daging Serigala',
        emoji: '🍖',
        rarity: 'Common',
        chance: 50,
        sellPrice: 15,
        type: 'material',
        description: 'Daging liar berotot',
      },
      {
        id: 'wolf_fang_necklace',
        name: 'Kalung Taring Serigala',
        emoji: '🐺📿',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 150,
        type: 'equipment',
        description: 'Kalung dari taring alpha. +ATK +Crit',
        stats: { atk: 8, critRate: 0.05 },
      },
      {
        id: 'claw',
        name: 'Cakar Serigala',
        emoji: '🐾',
        rarity: 'Uncommon',
        chance: 32,
        sellPrice: 25,
        type: 'material',
        description: 'Cakar tajam untuk kerajinan',
      },
      {
        id: 'pelt',
        name: 'Bulu Alpha',
        emoji: '🧶',
        rarity: 'Rare',
        chance: 5,
        sellPrice: 55,
        type: 'material',
        description: 'Bulu tebal pemimpin kawanan',
      },
      {
        id: 'eye_wolf',
        name: 'Mata Serigala',
        emoji: '👁️',
        rarity: 'Epic',
        chance: 10,
        sellPrice: 180,
        type: 'material',
        description: 'Mata yang masih menyala dalam gelap',
      },
    ],
  },
  {
    name: 'Cave Bear',
    emoji: '🐻',
    hp: 120,
    dmg: [18, 28],
    minLevel: 5,
    xp: 45,
    drops: [
      {
        id: 'bear_meat',
        name: 'Daging Beruang',
        emoji: '🥩',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 35,
        type: 'material',
        description: 'Daging berlemak dari gua',
      },
      {
        id: 'bear_paw_gauntlet',
        name: 'Gauntlet Cakar Beruang',
        emoji: '🐻🧤',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 180,
        type: 'equipment',
        description: 'Sarung tangan dari cakar beruang. +ATK +HP',
        stats: { atk: 10, hp: 20 },
        classLock: ['warrior'],
      },
      {
        id: 'honey',
        name: 'Madu Liar',
        emoji: '🍯',
        rarity: 'Uncommon',
        chance: 15,
        sellPrice: 30,
        type: 'consumable',
        description: 'Madu manis, pulihkan 25 HP',
        effects: [{ type: 'heal', value: 25 }],
      },
      {
        id: 'bear_claw',
        name: 'Cakar Beruang',
        emoji: '🐾',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 80,
        type: 'material',
        description: 'Cakar besar penghancur',
      },
      {
        id: 'heart_alpha',
        name: 'Jantung Alpha',
        emoji: '❤️‍🔥',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 400,
        type: 'consumable',
        description: 'Jantung alpha, pulihkan 60 HP',
        effects: [{ type: 'heal', value: 60 }],
      },
    ],
  },
  {
    name: 'Skeleton Warrior',
    emoji: '💀',
    hp: 110,
    dmg: [16, 26],
    minLevel: 5,
    xp: 42,
    drops: [
      {
        id: 'bone',
        name: 'Tulang Rusuk',
        emoji: '🦴',
        rarity: 'Common',
        chance: 52,
        sellPrice: 18,
        type: 'material',
        description: 'Tulang keras prajurit kuno',
      },
      {
        id: 'rusted_sword',
        name: 'Pedang Karat',
        emoji: '⚔️',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 45,
        type: 'equipment',
        description: 'Masih bisa diasah',
        stats: { atk: 8 },
        classLock: ['warrior'],
      },
      {
        id: 'bone_helm',
        name: 'Helm Tengkorak',
        emoji: '💀⛑️',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 160,
        type: 'equipment',
        description: 'Helm dari tengkorak. +DEF +HP',
        stats: { def: 3, hp: 15 },
      },
      {
        id: 'skull',
        name: 'Tengkorak',
        emoji: '💀',
        rarity: 'Rare',
        chance: 12,
        sellPrice: 95,
        type: 'material',
        description: 'Dipakai untuk ritual',
      },
      {
        id: 'soul_shard',
        name: 'Pecahan Jiwa',
        emoji: '🔮',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 220,
        type: 'material',
        description: 'Berbisik pelan',
      },
    ],
  },
  {
    name: 'Venom Spider',
    emoji: '🕷️',
    hp: 95,
    dmg: [14, 24],
    minLevel: 6,
    xp: 48,
    drops: [
      {
        id: 'spider_silk',
        name: 'Sutra Laba-laba',
        emoji: '🕸️',
        rarity: 'Common',
        chance: 50,
        sellPrice: 22,
        type: 'material',
        description: 'Kuat dan lengket',
      },
      {
        id: 'spider_fang_dagger',
        name: 'Belati Taring Laba-laba',
        emoji: '🗡️🕷️',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 200,
        type: 'equipment',
        description: 'Belati beracun. +ATK +CritDmg',
        stats: { atk: 14, critDmg: 0.3 },
        classLock: ['rogue'],
      },
      {
        id: 'venom_sac',
        name: 'Kantung Bisa',
        emoji: '🧪',
        rarity: 'Uncommon',
        chance: 32,
        sellPrice: 55,
        type: 'consumable',
        description: 'Ekstrak bisa, +20 stamina',
        effects: [{ type: 'stamina', value: 20 }],
      },
      {
        id: 'spider_fang',
        name: 'Taring Berbisa',
        emoji: '🦷',
        rarity: 'Rare',
        chance: 12,
        sellPrice: 110,
        type: 'material',
        description: 'Menetes hijau',
      },
      {
        id: 'spider_eye',
        name: 'Mata Majemuk',
        emoji: '👁️',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 250,
        type: 'material',
        description: 'Melihat 360°',
      },
    ],
  },
  {
    name: 'Harpy',
    emoji: '🦅',
    hp: 105,
    dmg: [17, 27],
    minLevel: 7,
    xp: 52,
    drops: [
      {
        id: 'feather',
        name: 'Bulu Harpy',
        emoji: '🪶',
        rarity: 'Common',
        chance: 52,
        sellPrice: 20,
        type: 'material',
        description: 'Ringan seperti angin',
      },
      {
        id: 'harpy_bow',
        name: 'Busur Harpy',
        emoji: '🏹🦅',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 220,
        type: 'equipment',
        description: 'Busur dari sayap harpy. +ATK +CritRate',
        stats: { atk: 16, critRate: 0.06 },
        classLock: ['rogue'],
      },
      {
        id: 'talon',
        name: 'Cakar Tajam',
        emoji: '🦅',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 60,
        type: 'material',
        description: 'Mencabik baja',
      },
      {
        id: 'wind_essence',
        name: 'Esensi Angin',
        emoji: '💨',
        rarity: 'Rare',
        chance: 12,
        sellPrice: 130,
        type: 'consumable',
        description: 'Hembusan angin, +25 stamina',
        effects: [{ type: 'stamina', value: 25 }],
      },
      {
        id: 'harpy_egg',
        name: 'Telur Harpy',
        emoji: '🥚',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 280,
        type: 'consumable',
        description: 'Telur langka, +45 HP',
        effects: [{ type: 'heal', value: 45 }],
      },
    ],
  },
  {
    name: 'Orc Berserker',
    emoji: '👹',
    hp: 140,
    dmg: [20, 32],
    minLevel: 8,
    xp: 60,
    drops: [
      {
        id: 'orc_tooth',
        name: 'Gigi Orc',
        emoji: '🦷',
        rarity: 'Common',
        chance: 47,
        sellPrice: 25,
        type: 'material',
        description: 'Besar dan kuning',
      },
      {
        id: 'war_axe',
        name: 'Kapak Perang',
        emoji: '🪓',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 70,
        type: 'equipment',
        description: 'Berat tapi mematikan',
        stats: { atk: 12 },
        classLock: ['warrior'],
      },
      {
        id: 'berserker_armor',
        name: 'Armor Berserk',
        emoji: '👹🛡️',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 400,
        type: 'equipment',
        description: 'Armor orc berserk. +ATK +HP +DEF',
        stats: { atk: 15, hp: 30, def: 4 },
        classLock: ['warrior'],
      },
      {
        id: 'berserk_blood',
        name: 'Darah Berserk',
        emoji: '🩸',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 140,
        type: 'consumable',
        description: 'Ramuan amarah, +15 ATK 10m',
        effects: [{ type: 'buff', value: 15 }],
      },
      {
        id: 'orc_warchief_helm',
        name: 'Helm Warchief',
        emoji: '⛑️',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 520,
        type: 'equipment',
        description: 'Mahkota para orc',
        stats: { hp: 35, def: 5, critRate: 0.05 },
      },
    ],
  },
  {
    name: 'Shadow Panther',
    emoji: '🐆',
    hp: 130,
    dmg: [22, 34],
    minLevel: 9,
    xp: 65,
    drops: [
      {
        id: 'panther_pelt',
        name: 'Kulit Bayangan',
        emoji: '🖤',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 65,
        type: 'material',
        description: 'Menyerap cahaya',
      },
      {
        id: 'shadow_cloak',
        name: 'Jubah Bayangan',
        emoji: '🥷🌑',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 450,
        type: 'equipment',
        description: 'Jubah panther. +CritRate +ATK',
        stats: { critRate: 0.08, atk: 12 },
        classLock: ['rogue'],
      },
      {
        id: 'shadow_claw',
        name: 'Cakar Bayangan',
        emoji: '🐾',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 125,
        type: 'material',
        description: 'Meninggalkan jejak hitam',
      },
      {
        id: 'night_essence',
        name: 'Esensi Malam',
        emoji: '🌑',
        rarity: 'Epic',
        chance: 15,
        sellPrice: 260,
        type: 'consumable',
        description: 'Esensi pekat, +30 stamina',
        effects: [{ type: 'stamina', value: 30 }],
      },
      {
        id: 'panther_heart',
        name: 'Jantung Panther',
        emoji: '🖤',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 580,
        type: 'consumable',
        description: 'Jantung bayangan, +70 HP',
        effects: [{ type: 'heal', value: 70 }],
      },
    ],
  },
  {
    name: 'Lava Slime',
    emoji: '🟠',
    hp: 150,
    dmg: [18, 30],
    minLevel: 10,
    xp: 70,
    drops: [
      {
        id: 'slime_core',
        name: 'Inti Slime',
        emoji: '🧡',
        rarity: 'Common',
        chance: 42,
        sellPrice: 30,
        type: 'material',
        description: 'Hangat terus',
      },
      {
        id: 'lava_boots',
        name: 'Sepatu Lava',
        emoji: '👢🔥',
        rarity: 'Rare',
        chance: 3,
        sellPrice: 200,
        type: 'equipment',
        description: 'Sepatu tahan lava. +HP +DEF',
        stats: { hp: 25, def: 3 },
      },
      {
        id: 'magma_jelly',
        name: 'Jeli Magma',
        emoji: '🍮',
        rarity: 'Uncommon',
        chance: 35,
        sellPrice: 75,
        type: 'consumable',
        description: 'Jeli pedas, +35 HP',
        effects: [{ type: 'heal', value: 35 }],
      },
      {
        id: 'fire_crystal',
        name: 'Kristal Api',
        emoji: '🔥',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 160,
        type: 'material',
        description: 'Menyala tanpa henti',
      },
      {
        id: 'core_lava',
        name: 'Jantung Lava',
        emoji: '❤️‍🔥',
        rarity: 'Epic',
        chance: 5,
        sellPrice: 320,
        type: 'consumable',
        description: 'Inti panas, +40 stamina',
        effects: [{ type: 'stamina', value: 40 }],
      },
    ],
  },
  {
    name: 'Frost Troll',
    emoji: '🧌',
    hp: 180,
    dmg: [24, 36],
    minLevel: 12,
    xp: 85,
    drops: [
      {
        id: 'troll_fat',
        name: 'Lemak Troll',
        emoji: '🧈',
        rarity: 'Common',
        chance: 42,
        sellPrice: 40,
        type: 'material',
        description: 'Tidak pernah beku',
      },
      {
        id: 'ice_club',
        name: 'Gada Es',
        emoji: '🥶',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 95,
        type: 'equipment',
        description: 'Membekukan musuh',
        stats: { atk: 18, def: 2 },
        classLock: ['warrior'],
      },
      {
        id: 'frost_cape',
        name: 'Jubah Beku',
        emoji: '🧥❄️',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 480,
        type: 'equipment',
        description: 'Jubah troll es. +HP +DEF +CritDmg',
        stats: { hp: 45, def: 6, critDmg: 0.2 },
      },
      {
        id: 'frost_heart',
        name: 'Jantung Beku',
        emoji: '💙',
        rarity: 'Rare',
        chance: 18,
        sellPrice: 190,
        type: 'consumable',
        description: 'Jantung es, +50 HP',
        effects: [{ type: 'heal', value: 50 }],
      },
      {
        id: 'troll_regen',
        name: 'Darah Regenerasi',
        emoji: '💧',
        rarity: 'Epic',
        chance: 7,
        sellPrice: 380,
        type: 'consumable',
        description: 'Darah troll, +90 HP',
        effects: [{ type: 'heal', value: 90 }],
      },
    ],
  },
  {
    name: 'Sand Worm',
    emoji: '🪱',
    hp: 200,
    dmg: [26, 40],
    minLevel: 14,
    xp: 95,
    drops: [
      {
        id: 'worm_meat',
        name: 'Daging Cacing',
        emoji: '🥩',
        rarity: 'Common',
        chance: 47,
        sellPrice: 45,
        type: 'consumable',
        description: 'Daging kenyal, +30 HP',
        effects: [{ type: 'heal', value: 30 }],
      },
      {
        id: 'sand_pearl',
        name: 'Mutiara Pasir',
        emoji: '⚪',
        rarity: 'Uncommon',
        chance: 30,
        sellPrice: 110,
        type: 'material',
        description: 'Terbentuk ribuan tahun',
      },
      {
        id: 'desert_scale_armor',
        name: 'Armor Sisik Gurun',
        emoji: '🛡️🏜️',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 550,
        type: 'equipment',
        description: 'Armor cacing gurun. +HP +DEF +ATK',
        stats: { hp: 40, def: 7, atk: 10 },
      },
      {
        id: 'desert_scale',
        name: 'Sisik Gurun',
        emoji: '🏜️',
        rarity: 'Rare',
        chance: 15,
        sellPrice: 210,
        type: 'material',
        description: 'Tahan panas',
      },
      {
        id: 'worm_tooth',
        name: 'Gigi Raksasa',
        emoji: '🦷',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 650,
        type: 'material',
        description: 'Sebesar pedang',
      },
    ],
  },
  {
    name: 'Dark Knight',
    emoji: '🗡️',
    hp: 220,
    dmg: [28, 42],
    minLevel: 15,
    xp: 105,
    drops: [
      {
        id: 'dark_steel',
        name: 'Baja Hitam',
        emoji: '⚫',
        rarity: 'Uncommon',
        chance: 42,
        sellPrice: 120,
        type: 'material',
        description: 'Tidak berkarat',
      },
      {
        id: 'cursed_blade',
        name: 'Pedang Terkutuk',
        emoji: '🗡️',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 240,
        type: 'equipment',
        description: 'Haus darah',
        stats: { atk: 22, critRate: 0.06 },
        classLock: ['warrior'],
      },
      {
        id: 'void_armor',
        name: 'Armor Void',
        emoji: '🛡️🕳️',
        rarity: 'Legendary',
        chance: 3,
        sellPrice: 900,
        type: 'equipment',
        description: 'Armor kegelapan. +DEF +HP +ATK',
        stats: { def: 10, hp: 50, atk: 15 },
      },
      {
        id: 'knight_emblem',
        name: 'Lambang Kegelapan',
        emoji: '🛡️',
        rarity: 'Epic',
        chance: 20,
        sellPrice: 420,
        type: 'material',
        description: 'Simbol kehormatan',
      },
      {
        id: 'void_essence',
        name: 'Esensi Void',
        emoji: '🕳️',
        rarity: 'Legendary',
        chance: 5,
        sellPrice: 780,
        type: 'consumable',
        description: 'Esensi kehampaan, +50 stamina',
        effects: [{ type: 'stamina', value: 50 }],
      },
    ],
  },
  {
    name: 'Thunder Eagle',
    emoji: '⚡',
    hp: 190,
    dmg: [30, 45],
    minLevel: 17,
    xp: 115,
    drops: [
      {
        id: 'storm_feather',
        name: 'Bulu Badai',
        emoji: '🪶',
        rarity: 'Uncommon',
        chance: 42,
        sellPrice: 130,
        type: 'material',
        description: 'Berderak listrik',
      },
      {
        id: 'eagle_talon',
        name: 'Cakar Petir',
        emoji: '⚡',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 250,
        type: 'material',
        description: 'Menyambar',
      },
      {
        id: 'thunder_bow',
        name: 'Busur Petir',
        emoji: '🏹⚡',
        rarity: 'Epic',
        chance: 3,
        sellPrice: 600,
        type: 'equipment',
        description: 'Busur elang petir. +ATK +CritRate +CritDmg',
        stats: { atk: 25, critRate: 0.08, critDmg: 0.3 },
        classLock: ['rogue'],
      },
      {
        id: 'thunder_egg',
        name: 'Telur Petir',
        emoji: '🥚',
        rarity: 'Epic',
        chance: 20,
        sellPrice: 460,
        type: 'consumable',
        description: 'Telur badai, +80 HP',
        effects: [{ type: 'heal', value: 80 }],
      },
      {
        id: 'storm_core',
        name: 'Inti Badai',
        emoji: '🌩️',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 1200,
        type: 'consumable',
        description: 'Jantung langit, +70 stamina',
        effects: [{ type: 'stamina', value: 70 }],
      },
    ],
  },
  {
    name: 'Crystal Golem',
    emoji: '💎',
    hp: 260,
    dmg: [25, 38],
    minLevel: 19,
    xp: 130,
    drops: [
      {
        id: 'crystal_shard',
        name: 'Pecahan Kristal',
        emoji: '🔹',
        rarity: 'Uncommon',
        chance: 47,
        sellPrice: 140,
        type: 'material',
        description: 'Berkilau',
      },
      {
        id: 'golem_core',
        name: 'Inti Golem',
        emoji: '🔷',
        rarity: 'Rare',
        chance: 30,
        sellPrice: 280,
        type: 'material',
        description: 'Berdenyut mana',
      },
      {
        id: 'crystal_staff',
        name: 'Tongkat Kristal',
        emoji: '🪄💎',
        rarity: 'Legendary',
        chance: 3,
        sellPrice: 1100,
        type: 'equipment',
        description: 'Tongkat golem kristal. +ATK +CritDmg +HP',
        stats: { atk: 28, critDmg: 0.4, hp: 30 },
        classLock: ['mage'],
      },
      {
        id: 'prism',
        name: 'Prisma Murni',
        emoji: '✨',
        rarity: 'Epic',
        chance: 15,
        sellPrice: 520,
        type: 'material',
        description: 'Memecah cahaya',
      },
      {
        id: 'diamond_heart',
        name: 'Hati Berlian',
        emoji: '💠',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 1500,
        type: 'consumable',
        description: 'Hati berlian, +150 HP',
        effects: [{ type: 'heal', value: 150 }],
      },
    ],
  },
  {
    name: 'Hydra',
    emoji: '🐉',
    hp: 320,
    dmg: [32, 48],
    minLevel: 22,
    xp: 160,
    drops: [
      {
        id: 'hydra_scale',
        name: 'Sisik Hydra',
        emoji: '🐍',
        rarity: 'Rare',
        chance: 37,
        sellPrice: 300,
        type: 'material',
        description: 'Tahan asam',
      },
      {
        id: 'hydra_head',
        name: 'Kepala Hydra',
        emoji: '🐉',
        rarity: 'Epic',
        chance: 35,
        sellPrice: 580,
        type: 'material',
        description: 'Tumbuh lagi?',
      },
      {
        id: 'hydra_venom_dagger',
        name: 'Belati Bisa Hydra',
        emoji: '🗡️🐉',
        rarity: 'Legendary',
        chance: 3,
        sellPrice: 1200,
        type: 'equipment',
        description: 'Belati dari kepala hydra. +ATK +Crit +CritDmg',
        stats: { atk: 35, critRate: 0.1, critDmg: 0.4 },
        classLock: ['rogue'],
      },
      {
        id: 'venom_blood',
        name: 'Darah Beracun',
        emoji: '☠️',
        rarity: 'Legendary',
        chance: 20,
        sellPrice: 950,
        type: 'consumable',
        description: 'Darah hydra, +25 ATK',
        effects: [{ type: 'buff', value: 25 }],
      },
      {
        id: 'hydra_heart',
        name: 'Jantung Hydra',
        emoji: '💚',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 2100,
        type: 'consumable',
        description: 'Sembilan denyut, +200 HP',
        effects: [{ type: 'heal', value: 200 }],
      },
    ],
  },
  {
    name: 'Phoenix',
    emoji: '🔥',
    hp: 300,
    dmg: [35, 52],
    minLevel: 25,
    xp: 185,
    drops: [
      {
        id: 'ash_feather',
        name: 'Bulu Abu',
        emoji: '🪶',
        rarity: 'Rare',
        chance: 37,
        sellPrice: 340,
        type: 'material',
        description: 'Hangat',
      },
      {
        id: 'flame_talon',
        name: 'Cakar Api',
        emoji: '🔥',
        rarity: 'Epic',
        chance: 35,
        sellPrice: 650,
        type: 'material',
        description: 'Membara',
      },
      {
        id: 'phoenix_wings',
        name: 'Sayap Phoenix',
        emoji: '🔥🪽',
        rarity: 'Mythic',
        chance: 3,
        sellPrice: 3000,
        type: 'equipment',
        description: 'Sayap phoenix. +ATK +CritDmg +HP +Stamina',
        stats: { atk: 40, critDmg: 0.5, hp: 60 },
        classLock: ['mage'],
      },
      {
        id: 'phoenix_tear',
        name: 'Air Mata Phoenix',
        emoji: '💧',
        rarity: 'Legendary',
        chance: 20,
        sellPrice: 1100,
        type: 'consumable',
        description: 'Air mata suci, +180 HP & +50 stamina',
        effects: [
          { type: 'heal', value: 180 },
          { type: 'stamina', value: 50 },
        ],
      },
      {
        id: 'rebirth_egg',
        name: 'Telur Kelahiran',
        emoji: '🥚',
        rarity: 'Mythic',
        chance: 5,
        sellPrice: 2500,
        type: 'consumable',
        description: 'Kelahiran kembali, +100 stamina & +50 HP',
        effects: [
          { type: 'stamina', value: 100 },
          { type: 'heal', value: 50 },
        ],
      },
    ],
  },
];

export function getScaledMonster(userLevel: number) {
  const available = BASE_MONSTERS.filter((m) => userLevel >= m.minLevel);
  const base = available[Math.floor(Math.random() * available.length)];
  const diff = userLevel - base.minLevel;
  const hpScale = 1 + diff * 0.12;
  const dmgScale = 1 + diff * 0.08;
  return {
    ...base,
    hp: Math.floor(base.hp * hpScale),
    dmg: [Math.floor(base.dmg[0] * dmgScale), Math.floor(base.dmg[1] * dmgScale)] as [
      number,
      number,
    ],
    xp: Math.floor(base.xp * hpScale),
    level: userLevel,
  };
}
