import { ItemInput } from './inventory';

export interface Ingredient {
  id: string;
  qty: number;
}

export interface Recipe {
  id: string;
  name: string;
  emoji: string;
  ingredients: Ingredient[];
  resultItemId: string;
  exp: number;
  levelReq?: number;
}

export const RECIPES: Recipe[] = [
  // === BASIC ===
  {
    id: 'fish_sardine',
    name: 'Sarden Bakar',
    emoji: '🐟',
    ingredients: [{ id: 'fish_sardine', qty: 1 }],
    resultItemId: 'cooked_sardine',
    exp: 5,
  },
  {
    id: 'fish_mackerel',
    name: 'Kembung Goreng',
    emoji: '🐟',
    ingredients: [{ id: 'fish_mackerel', qty: 1 }],
    resultItemId: 'cooked_mackerel',
    exp: 6,
  },
  {
    id: 'fish_tilapia',
    name: 'Nila Bakar',
    emoji: '🐠',
    ingredients: [{ id: 'fish_tilapia', qty: 1 }],
    resultItemId: 'cooked_tilapia',
    exp: 7,
  },
  {
    id: 'fish_salmon',
    name: 'Salmon Panggang',
    emoji: '🍣',
    ingredients: [{ id: 'fish_salmon', qty: 1 }],
    resultItemId: 'cooked_salmon',
    exp: 10,
  },
  {
    id: 'fish_tuna',
    name: 'Tuna Steak',
    emoji: '🐟',
    ingredients: [{ id: 'fish_tuna', qty: 1 }],
    resultItemId: 'cooked_tuna',
    exp: 9,
  },
  {
    id: 'meat',
    name: 'Steak Daging',
    emoji: '🥩',
    ingredients: [{ id: 'meat', qty: 1 }],
    resultItemId: 'cooked_meat',
    exp: 7,
  },
  {
    id: 'hide',
    name: 'Sup Kulit',
    emoji: '🦌',
    ingredients: [{ id: 'hide', qty: 1 }],
    resultItemId: 'hide_soup',
    exp: 4,
  },
  {
    id: 'wolf_meat',
    name: 'Steak Serigala',
    emoji: '🍖',
    ingredients: [{ id: 'wolf_meat', qty: 1 }],
    resultItemId: 'cooked_wolf',
    exp: 8,
  },
  {
    id: 'bear_meat',
    name: 'Bear Steak',
    emoji: '🥩',
    ingredients: [{ id: 'bear_meat', qty: 1 }],
    resultItemId: 'cooked_bear',
    exp: 15,
  },
  {
    id: 'lizard_meat',
    name: 'Sate Kadal',
    emoji: '🍗',
    ingredients: [{ id: 'lizard_meat', qty: 1 }],
    resultItemId: 'cooked_lizard',
    exp: 6,
  },
  {
    id: 'honey',
    name: 'Madu Hangat',
    emoji: '🍯',
    ingredients: [{ id: 'honey', qty: 1 }],
    resultItemId: 'warm_honey',
    exp: 8,
  },

  // === BUFF BASIC ===
  {
    id: 'spicy_stew',
    name: 'Spicy Stew',
    emoji: '🌶️',
    ingredients: [
      { id: 'meat', qty: 2 },
      { id: 'chili', qty: 1 },
    ],
    resultItemId: 'spicy_stew',
    exp: 12,
  },
  {
    id: 'herbal_tea',
    name: 'Herbal Tea',
    emoji: '🍵',
    ingredients: [
      { id: 'herb', qty: 1 },
      { id: 'honey', qty: 1 },
    ],
    resultItemId: 'herbal_tea',
    exp: 10,
  },
  {
    id: 'mushroom_soup',
    name: 'Sup Jamur',
    emoji: '🍄',
    ingredients: [
      { id: 'mushroom', qty: 3 },
      { id: 'bark', qty: 1 },
    ],
    resultItemId: 'mushroom_soup',
    exp: 9,
  },
  {
    id: 'ginseng_brew',
    name: 'Ginseng Brew',
    emoji: '🌱',
    ingredients: [
      { id: 'root', qty: 2 },
      { id: 'honey', qty: 1 },
    ],
    resultItemId: 'ginseng_brew',
    exp: 14,
  },
  {
    id: 'mana_potion',
    name: 'Mana Potion',
    emoji: '🔷',
    ingredients: [
      { id: 'mana_crystal', qty: 1 },
      { id: 'herb', qty: 1 },
      { id: 'bark', qty: 1 },
    ],
    resultItemId: 'mana_potion',
    exp: 15,
  },
  {
    id: 'bark_tea',
    name: 'Bark Tea',
    emoji: '🪵',
    ingredients: [
      { id: 'bark', qty: 2 },
      { id: 'mushroom', qty: 1 },
    ],
    resultItemId: 'bark_tea',
    exp: 7,
  },
  {
    id: 'moon_elixir',
    name: 'Moon Elixir',
    emoji: '🌸',
    ingredients: [
      { id: 'moonflower', qty: 1 },
      { id: 'mana_crystal', qty: 2 },
      { id: 'honey', qty: 2 },
    ],
    resultItemId: 'moon_elixir',
    exp: 20,
  },
  {
    id: 'golden_omelette',
    name: 'Golden Omelette',
    emoji: '🥚',
    ingredients: [
      { id: 'monster_egg', qty: 1 },
      { id: 'gold_nugget', qty: 1 },
      { id: 'bear_meat', qty: 1 },
    ],
    resultItemId: 'golden_omelette',
    exp: 25,
  },

  // === MID GAME ===
  {
    id: 'venom_soup',
    name: 'Venom Soup',
    emoji: '🧪',
    ingredients: [
      { id: 'venom_sac', qty: 1 },
      { id: 'lizard_meat', qty: 1 },
    ],
    resultItemId: 'venom_soup',
    exp: 18,
  },
  {
    id: 'spider_silk_pie',
    name: 'Silk Pie',
    emoji: '🕸️',
    ingredients: [
      { id: 'spider_silk', qty: 3 },
      { id: 'honey', qty: 1 },
    ],
    resultItemId: 'silk_pie',
    exp: 16,
  },
  {
    id: 'harpy_wings',
    name: 'Crispy Harpy',
    emoji: '🦅',
    ingredients: [
      { id: 'feather', qty: 5 },
      { id: 'talon', qty: 2 },
    ],
    resultItemId: 'crispy_harpy',
    exp: 17,
  },
  {
    id: 'berserk_stew',
    name: 'Berserk Stew',
    emoji: '🩸',
    ingredients: [
      { id: 'berserk_blood', qty: 1 },
      { id: 'orc_tooth', qty: 3 },
      { id: 'bear_meat', qty: 1 },
    ],
    resultItemId: 'berserk_stew',
    exp: 22,
  },
  {
    id: 'shadow_curry',
    name: 'Shadow Curry',
    emoji: '🐆',
    ingredients: [
      { id: 'panther_pelt', qty: 2 },
      { id: 'night_essence', qty: 1 },
    ],
    resultItemId: 'shadow_curry',
    exp: 24,
  },
  {
    id: 'lava_jelly',
    name: 'Lava Jelly',
    emoji: '🟠',
    ingredients: [
      { id: 'magma_jelly', qty: 2 },
      { id: 'core_lava', qty: 1 },
    ],
    resultItemId: 'lava_jelly',
    exp: 20,
  },

  // === LATE GAME ===
  {
    id: 'troll_ragout',
    name: 'Troll Ragout',
    emoji: '🧌',
    ingredients: [
      { id: 'troll_fat', qty: 2 },
      { id: 'frost_heart', qty: 1 },
    ],
    resultItemId: 'troll_ragout',
    exp: 28,
  },
  {
    id: 'worm_sushi',
    name: 'Worm Sushi',
    emoji: '🪱',
    ingredients: [
      { id: 'worm_meat', qty: 2 },
      { id: 'sand_pearl', qty: 1 },
    ],
    resultItemId: 'worm_sushi',
    exp: 30,
  },
  {
    id: 'dark_knight_feast',
    name: 'Knight Feast',
    emoji: '🗡️',
    ingredients: [
      { id: 'dark_steel', qty: 1 },
      { id: 'void_essence', qty: 1 },
      { id: 'bear_meat', qty: 2 },
    ],
    resultItemId: 'knight_feast',
    exp: 35,
  },
  {
    id: 'storm_broth',
    name: 'Storm Broth',
    emoji: '⚡',
    ingredients: [
      { id: 'storm_feather', qty: 3 },
      { id: 'thunder_egg', qty: 1 },
    ],
    resultItemId: 'storm_broth',
    exp: 38,
  },
  {
    id: 'crystal_soup',
    name: 'Crystal Soup',
    emoji: '💎',
    ingredients: [
      { id: 'crystal_shard', qty: 5 },
      { id: 'prism', qty: 1 },
      { id: 'diamond_heart', qty: 1 },
    ],
    resultItemId: 'crystal_soup',
    exp: 45,
  },

  // === END GAME ===
  {
    id: 'hydra_gumbo',
    name: 'Hydra Gumbo',
    emoji: '🐉',
    ingredients: [
      { id: 'hydra_scale', qty: 3 },
      { id: 'hydra_head', qty: 1 },
      { id: 'venom_blood', qty: 1 },
    ],
    resultItemId: 'hydra_gumbo',
    exp: 55,
  },
  {
    id: 'phoenix_rebirth',
    name: 'Phoenix Rebirth',
    emoji: '🔥',
    ingredients: [
      { id: 'phoenix_tear', qty: 1 },
      { id: 'rebirth_egg', qty: 1 },
      { id: 'flame_talon', qty: 2 },
    ],
    resultItemId: 'phoenix_rebirth',
    exp: 65,
  },

  // === DUNGEON SPECIALS ===
  {
    id: 'slime_jelly',
    name: 'Slime Jelly',
    emoji: '🟢',
    ingredients: [
      { id: 'slime_core', qty: 2 },
      { id: 'gooey_jelly', qty: 1 },
    ],
    resultItemId: 'slime_jelly',
    exp: 12,
  },
  {
    id: 'void_soup',
    name: 'Void Soup',
    emoji: '🌫️',
    ingredients: [
      { id: 'void_essence', qty: 2 },
      { id: 'soul_wisp', qty: 1 },
      { id: 'ectoplasm', qty: 3 },
    ],
    resultItemId: 'void_soup',
    exp: 50,
  },
  {
    id: 'drake_flame_grill',
    name: 'Drake Flame Grill',
    emoji: '🐲',
    ingredients: [
      { id: 'drake_scale', qty: 4 },
      { id: 'drake_claw', qty: 2 },
      { id: 'charred_bone', qty: 1 },
    ],
    resultItemId: 'drake_grill',
    exp: 60,
  },
];

export const getRecipe = (id: string) => RECIPES.find((r) => r.id === id);

// === ITEM DEFINITIONS FOR DB SEED - 100% match Item.ts schema ===
export const COOKED_ITEMS: ItemInput[] = [
  {
    itemId: 'cooked_sardine',
    name: 'Sarden Bakar',
    emoji: '🐟',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 20 HP',
    sellPrice: 8,
    effects: [{ type: 'heal', value: 20 }],
  },
  {
    itemId: 'cooked_mackerel',
    name: 'Kembung Goreng',
    emoji: '🐟',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 25 HP',
    sellPrice: 10,
    effects: [{ type: 'heal', value: 25 }],
  },
  {
    itemId: 'cooked_tilapia',
    name: 'Nila Bakar',
    emoji: '🐠',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 30 HP',
    sellPrice: 12,
    effects: [{ type: 'heal', value: 30 }],
  },
  {
    itemId: 'cooked_salmon',
    name: 'Salmon Panggang',
    emoji: '🍣',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 45 HP',
    sellPrice: 20,
    effects: [{ type: 'heal', value: 45 }],
  },
  {
    itemId: 'cooked_tuna',
    name: 'Tuna Steak',
    emoji: '🐟',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 40 HP',
    sellPrice: 18,
    effects: [{ type: 'heal', value: 40 }],
  },
  {
    itemId: 'cooked_meat',
    name: 'Steak Daging',
    emoji: '🥩',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 30 HP',
    sellPrice: 12,
    effects: [{ type: 'heal', value: 30 }],
  },
  {
    itemId: 'hide_soup',
    name: 'Sup Kulit',
    emoji: '🦌',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 15 HP',
    sellPrice: 6,
    effects: [{ type: 'heal', value: 15 }],
  },
  {
    itemId: 'cooked_wolf',
    name: 'Steak Serigala',
    emoji: '🍖',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 35 HP',
    sellPrice: 14,
    effects: [{ type: 'heal', value: 35 }],
  },
  {
    itemId: 'cooked_bear',
    name: 'Bear Steak',
    emoji: '🥩',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 70 HP',
    sellPrice: 35,
    effects: [{ type: 'heal', value: 70 }],
  },
  {
    itemId: 'cooked_lizard',
    name: 'Sate Kadal',
    emoji: '🍗',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 25 HP',
    sellPrice: 10,
    effects: [{ type: 'heal', value: 25 }],
  },
  {
    itemId: 'warm_honey',
    name: 'Madu Hangat',
    emoji: '🍯',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 40 HP',
    sellPrice: 18,
    effects: [{ type: 'heal', value: 40 }],
  },
  {
    itemId: 'spicy_stew',
    name: 'Spicy Stew',
    emoji: '🌶️',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 40 HP + ATK boost',
    sellPrice: 25,
    effects: [
      { type: 'heal', value: 40 },
      { type: 'buff', value: 5 },
    ],
  },
  {
    itemId: 'herbal_tea',
    name: 'Herbal Tea',
    emoji: '🍵',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 25 HP + stamina regen',
    sellPrice: 15,
    effects: [
      { type: 'heal', value: 25 },
      { type: 'buff', value: 2 },
    ],
  },
  {
    itemId: 'mushroom_soup',
    name: 'Sup Jamur',
    emoji: '🍄',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 35 HP',
    sellPrice: 14,
    effects: [{ type: 'heal', value: 35 }],
  },
  {
    itemId: 'ginseng_brew',
    name: 'Ginseng Brew',
    emoji: '🌱',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 50 HP + stamina regen',
    sellPrice: 30,
    effects: [
      { type: 'heal', value: 50 },
      { type: 'buff', value: 3 },
    ],
  },
  {
    itemId: 'mana_potion',
    name: 'Mana Potion',
    emoji: '🔷',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 15 HP + ATK boost',
    sellPrice: 28,
    effects: [
      { type: 'heal', value: 15 },
      { type: 'buff', value: 8 },
    ],
  },
  {
    itemId: 'bark_tea',
    name: 'Bark Tea',
    emoji: '🪵',
    type: 'consumable',
    rarity: 'Common',
    description: 'Restores 20 HP',
    sellPrice: 8,
    effects: [{ type: 'heal', value: 20 }],
  },
  {
    itemId: 'moon_elixir',
    name: 'Moon Elixir',
    emoji: '🌸',
    type: 'consumable',
    rarity: 'Epic',
    description: 'Restores 80 HP + ATK boost',
    sellPrice: 60,
    effects: [
      { type: 'heal', value: 80 },
      { type: 'buff', value: 12 },
    ],
  },
  {
    itemId: 'golden_omelette',
    name: 'Golden Omelette',
    emoji: '🥚',
    type: 'consumable',
    rarity: 'Epic',
    description: 'Restores 100 HP + ATK boost',
    sellPrice: 80,
    effects: [
      { type: 'heal', value: 100 },
      { type: 'buff', value: 15 },
    ],
  },
  {
    itemId: 'venom_soup',
    name: 'Venom Soup',
    emoji: '🧪',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 45 HP + stamina regen',
    sellPrice: 30,
    effects: [
      { type: 'heal', value: 45 },
      { type: 'buff', value: 4 },
    ],
  },
  {
    itemId: 'silk_pie',
    name: 'Silk Pie',
    emoji: '🕸️',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 55 HP',
    sellPrice: 25,
    effects: [{ type: 'heal', value: 55 }],
  },
  {
    itemId: 'crispy_harpy',
    name: 'Crispy Harpy',
    emoji: '🦅',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 60 HP',
    sellPrice: 28,
    effects: [{ type: 'heal', value: 60 }],
  },
  {
    itemId: 'berserk_stew',
    name: 'Berserk Stew',
    emoji: '🩸',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 75 HP + ATK boost',
    sellPrice: 45,
    effects: [
      { type: 'heal', value: 75 },
      { type: 'buff', value: 10 },
    ],
  },
  {
    itemId: 'shadow_curry',
    name: 'Shadow Curry',
    emoji: '🐆',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 80 HP + stamina regen',
    sellPrice: 48,
    effects: [
      { type: 'heal', value: 80 },
      { type: 'buff', value: 5 },
    ],
  },
  {
    itemId: 'lava_jelly',
    name: 'Lava Jelly',
    emoji: '🟠',
    type: 'consumable',
    rarity: 'Rare',
    description: 'Restores 65 HP',
    sellPrice: 35,
    effects: [{ type: 'heal', value: 65 }],
  },
  {
    itemId: 'troll_ragout',
    name: 'Troll Ragout',
    emoji: '🧌',
    type: 'consumable',
    rarity: 'Epic',
    description: 'Restores 95 HP',
    sellPrice: 55,
    effects: [{ type: 'heal', value: 95 }],
  },
  {
    itemId: 'worm_sushi',
    name: 'Worm Sushi',
    emoji: '🪱',
    type: 'consumable',
    rarity: 'Epic',
    description: 'Restores 110 HP',
    sellPrice: 65,
    effects: [{ type: 'heal', value: 110 }],
  },
  {
    itemId: 'knight_feast',
    name: 'Knight Feast',
    emoji: '🗡️',
    type: 'consumable',
    rarity: 'Epic',
    description: 'Restores 125 HP + ATK boost',
    sellPrice: 85,
    effects: [
      { type: 'heal', value: 125 },
      { type: 'buff', value: 18 },
    ],
  },
  {
    itemId: 'storm_broth',
    name: 'Storm Broth',
    emoji: '⚡',
    type: 'consumable',
    rarity: 'Legendary',
    description: 'Restores 140 HP + stamina regen',
    sellPrice: 100,
    effects: [
      { type: 'heal', value: 140 },
      { type: 'buff', value: 7 },
    ],
  },
  {
    itemId: 'crystal_soup',
    name: 'Crystal Soup',
    emoji: '💎',
    type: 'consumable',
    rarity: 'Legendary',
    description: 'Restores 160 HP',
    sellPrice: 120,
    effects: [{ type: 'heal', value: 160 }],
  },
  {
    itemId: 'hydra_gumbo',
    name: 'Hydra Gumbo',
    emoji: '🐉',
    type: 'consumable',
    rarity: 'Legendary',
    description: 'Restores 200 HP + ATK boost',
    sellPrice: 180,
    effects: [
      { type: 'heal', value: 200 },
      { type: 'buff', value: 25 },
    ],
  },
  {
    itemId: 'phoenix_rebirth',
    name: 'Phoenix Rebirth',
    emoji: '🔥',
    type: 'consumable',
    rarity: 'Mythic',
    description: 'Restores 250 HP + ATK boost',
    sellPrice: 250,
    effects: [
      { type: 'heal', value: 250 },
      { type: 'buff', value: 30 },
    ],
  },
  {
    itemId: 'slime_jelly',
    name: 'Slime Jelly',
    emoji: '🟢',
    type: 'consumable',
    rarity: 'Uncommon',
    description: 'Restores 35 HP',
    sellPrice: 16,
    effects: [{ type: 'heal', value: 35 }],
  },
  {
    itemId: 'void_soup',
    name: 'Void Soup',
    emoji: '🌫️',
    type: 'consumable',
    rarity: 'Legendary',
    description: 'Restores 180 HP + stamina regen',
    sellPrice: 150,
    effects: [
      { type: 'heal', value: 180 },
      { type: 'buff', value: 8 },
    ],
  },
  {
    itemId: 'drake_grill',
    name: 'Drake Flame Grill',
    emoji: '🐲',
    type: 'consumable',
    rarity: 'Mythic',
    description: 'Restores 220 HP + ATK boost',
    sellPrice: 200,
    effects: [
      { type: 'heal', value: 220 },
      { type: 'buff', value: 22 },
    ],
  },
];
